### ISSUE TITLE
Export exports everything in default scene

### ISSUE THREAD

**Issue by jasonayre** [BabylonJS/Editor#103]
Using both the electron dmg provided, as well as building the electron app from source:

When I do an export (to .babylon format), it exports all the default materials, mesh, everything, even though I've deleted them, used the clean unused materials buttons, etc. 

Additionally, I cannot restore my scene (it just reloads the default scene (even if I choose not to append to current scene). - And reload not working either, it just reloads the default scene as well. - I would open separate issues, but given that basically nothing is working for me, I figured I'd check to make sure I wasn't doing something wrong first :)

p.s. Cool library though, I've been wanting a really basic babylon native editor for awhile now to build basic meshes/materials targeted specifically for babylon

**Comment by julien-moreau** [comment]
Thanks for reporting!
I'm trying to fix that issue, can you download the latest version here?: http://editor.babylonjs.com/BabylonJS Editor.dmg (uploaded 2mins ago :))

**Comment by jasonayre** [comment]
Ya, I just downloaded, reinstalled, still having same issue (everything being exported). Started with a new project, cleared it out again and retried, still no luck. -- Reload issue appears to be fixed however as far as I can tell (reloading scene didn't nuke it and replace it with the demo scene)

**Comment by jasonayre** [comment]
@julien-moreau  np! Just tried again, unfortunately, still seeing same issue :(
