### ISSUE TITLE
[V2]PBR Material: Reflective Texture doesn't work when I put a map in Metallic Texture, and why only Metalic, not Rougness

### ISSUE THREAD

**Issue by jk601220272** [BabylonJS/Editor#107]
![_15368468499249](https://user-images.githubusercontent.com/25475161/45492717-99a1c900-b79f-11e8-99f6-00c5c1169d0a.png)

**Comment by julien-moreau** [comment]
Hey just added metallic roughness and specular glossiness materials support.
What do you mean by "why only Metalic, not Rougness" ?

**Comment by jk601220272** [comment]
Sorry, my English is not good. I mean, why not provide rougness Property

**Comment by jk601220272** [comment]
![3424](https://user-images.githubusercontent.com/25475161/45524500-5bd58c80-b801-11e8-9fb1-09db03d9237f.png)

**Comment by julien-moreau** [comment]
No worry :)
I’ll deploy with the new materials I added
Anyway I suggest that you read this article in order to understand how to configure roughness http://doc.babylonjs.com/how_to/physically_based_rendering_master

**Comment by jk601220272** [comment]
Nice and Thank you for your suggestion!

**Comment by julien-moreau** [comment]
Deployed!
You can re-download from http://editor.babylonjs.com/BabylonJS%20Editor.exe :)
I'm waiting for a working mac to generate the mac os version. An officiel release will come soon
