### ISSUE TITLE
Destroy method on game object + trigger notifications to other objects

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Editor#118]
"Destroy method on game object life cycle could be useful for cleaning resources or trigger some event/notifications to other object"

@MisterLight do you mean notifications to notify another node in the scene? Or notify other scripts attached to the current object?

**Comment by MisterLight** [comment]
Im confused about a node, are you talking about a element in the hierarchy?

**Comment by julien-moreau** [comment]
Yes, the meshes, lights, cameras, particle systems, etc.

**Comment by MisterLight** [comment]
I would say notify to a script rather than a node, inside this script you could change the properties as you like.

**Comment by julien-moreau** [comment]
Hey @MisterLight added a way to send messages to other scripts of the object which has the attached script. Will be available in the 3.0.0 of the editor when 4.0 of babylonjs will be released :)
