### ISSUE TITLE
Unable to run in Electron

### ISSUE THREAD

**Issue by pchertok** [BabylonJS/Editor#12]
Would be awesome to be able to use the editor in [Electron ](https://github.com/electron/electron) as a Desktop Application but currently loading it into Electron as is produces quite a few runtime errors.

**Comment by julien-moreau** [comment]
Hey, this is exactly what @sevan did some months ago. We are planning to do some things with Electron since it can bring a lot of additional features. I'll share this issue to @sevan so he may help you with Electron and the Editor

**Comment by sevan** [comment]
I did?

**Comment by julien-moreau** [comment]
Oups, not you sorry for the mistake :)

**Comment by sevan** [comment]
:) no worries

**Comment by julien-moreau** [comment]
@pchertok after the v1.0 of the editor we'll try to focus on the Electron support and come with news about it. It may be a good added value for an editor :)
Just for informations, what kind of errors do you have ?

**Comment by julien-moreau** [comment]
I think this should one of your issues: http://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined

**Comment by julien-moreau** [comment]
Hey, I just pushed a working version of the Editor with Electron, I did it just to see how it works
On the branch "develop" you just have to install missing packages (npm install) and run the following commands:
- For OS X : gulp electron --osx --arch=x64 --platform=darwin
- For Win32 : gulp electron --win32 --arch=x64 --platform=win32
- For Linux : gulp electron --linux --arch=x64 --platform=linux
