### ISSUE TITLE
I love the idea of this editor, is there anyone working on this editor? I found some bugs

### ISSUE THREAD

**Issue by andrisole92** [BabylonJS/Editor#121]
Hi.

Basically, the exported template does not have the scripts attached, and there are some problems with them basically.

**Comment by julien-moreau** [comment]
Hi @andrisole92 !
Happy that you modified the title ^^
I'm currently working on the 3.0.0 that will fix all the known bugs and add new features such as multiple scene management.

I'm focusing on your bug right now and will share with you a new version before the 3.0.0 rises.
Anyway, if you are able to build the editor youself, you can use the branch feature/vscode which has the latest commit

**Comment by julien-moreau** [comment]
@andrisole92 reproduced and fixed!
Do you want me to share a Mac OS build? Or you prefer to build your one?

**Comment by andrisole92** [comment]
@julien-moreau , all right thanks!

I also found some things such as copy-paste is not working in the code-editor on Mac OS. By the way is it possible to open scripts with IntelliJ? I couldn't find the location.

**Comment by andrisole92** [comment]
@julien-moreau, are you looking to create a component-based architecture, like in Unity?

**Comment by julien-moreau** [comment]
Yes it is planned but that is a huge feature! The overall architecture tends to that feature but still requires changes before it can work well.

Will try to debug the Mac OS ASAP!
Also notified that undo/redo don’t work with the CMD+Z but CTRL+Z
