### ISSUE TITLE
Open and save project not working properly

### ISSUE THREAD

**Issue by manrix** [BabylonJS/Editor#124]
I'm using the electron app.
I open the app and the default scene is loaded. Then i create a new project and save it. I close the app and open the saved project again. It remains stuck at "Loading Scene..." and nothing happens.
If i open the saved project file i see it has references to the default scene assets.
Shouldn't it save the current scene ?

**Comment by julien-moreau** [comment]
Hey thanks for reporting!
I'm releasing the 3.0.0 today wich embeds a lot of users feedbacks and bug fixes.

The previous version of the editor has a default scene not intended to be saved or whatever. I think the editor adopted a bad phylosophy. Today it changed and you'll be able to save/load everything you save :)
Will let you know once released

**Comment by julien-moreau** [comment]
@manrix
It has been deployed!
You can download the 3.0.0 here: https://doc.babylonjs.com/resources/getting_started
Closing this issue has it has been fixed in the 3.0.0.
Thanks for reporting and don’t hesitate to report other bugs, it’ll be fixed ASAP :)
