### ISSUE TITLE
cannot compile vscode-extension Cannot find type definition file for 'vscode'.

### ISSUE THREAD

**Issue by azakariaMSFT** [BabylonJS/Editor#125]
When running "npm run build". i get an error when compiling the extension. is this known?
C:\babyEditor\vscode-extension>tsc -p .
error TS2688: Cannot find type definition file for 'vscode'.

I also suggest adding to the instructions those commands as those were causing packages are not getting automatically installed with npm i
npm install -g vsce
npm install -g typescript

full log 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle babylonjs-editor@3.0.0~precompile: babylonjs-editor@3.0.0
6 info lifecycle babylonjs-editor@3.0.0~compile: babylonjs-editor@3.0.0
7 verbose lifecycle babylonjs-editor@3.0.0~compile: unsafe-perm in lifecycle true
8 verbose lifecycle babylonjs-editor@3.0.0~compile: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\babyEditor\vscode-extension\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\babyEditor\vscode-extension\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\babyEditor\vscode-extension\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\babyEditor\vscode-extension\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\babyEditor\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\babyEditor\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\aiz-home\AppData\Local\Microsoft\WindowsApps;C:\Users\aiz-home\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\aiz-home\AppData\Roaming\npm
9 verbose lifecycle babylonjs-editor@3.0.0~compile: CWD: C:\babyEditor\vscode-extension
10 silly lifecycle babylonjs-editor@3.0.0~compile: Args: [ '/d /s /c', 'tsc -p .' ]
11 silly lifecycle babylonjs-editor@3.0.0~compile: Returned: code: 2  signal: null
12 info lifecycle babylonjs-editor@3.0.0~compile: Failed to exec compile script
13 verbose stack Error: babylonjs-editor@3.0.0 compile: `tsc -p .`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid babylonjs-editor@3.0.0
15 verbose cwd C:\babyEditor\vscode-extension
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error babylonjs-editor@3.0.0 compile: `tsc -p .`
22 error Exit status 2
23 error Failed at the babylonjs-editor@3.0.0 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by julien-moreau** [comment]
Hey @azakariaMSFT yes it known. You have to install the dependencies in the vscode-extension folder to build.
Just pushed on master to remove the vscode extension from main build command as its development has been paused until more important feature requests are done
Thanks :)

**Comment by azakariaMSFT** [comment]
Thanks for the quick response, works perfectly without it

**Comment by julien-moreau** [comment]
Happy !
Do you plan to contribute? If yes don’t hesitate to ask if something is not clear or whatever :)
Thanks!
