### ISSUE TITLE
I want to use a clear icon for the retina screen. And support for multiple languages.

### ISSUE THREAD

**Issue by sbfkcel** [BabylonJS/Editor#128]
I want to use a clear icon for the retina screen. And support for multiple languages.

**Comment by julien-moreau** [comment]
Keeping the issue opened and added to the todolist :)

For the icons, do you know any designer? I’m not having any skill in design to create icons :(

**Comment by sbfkcel** [comment]
If I can, I am happy to participate. Including editor ui

**Comment by dtrinh100** [comment]
Font Awesome 5 (https://fontawesome.com/) has a bunch of free icons that can be used for web applications. :)

**Comment by julien-moreau** [comment]
@dtrinh100 thanks! Will use that if I can work with also in offline mode (for the electron app) :)

@sbfkcel thanks for proposing! My main problem is that I’m just a noob in advanced HTML/CSS. 
@gotwig began working on the dark theme which is still a user request. Do you mind trying to improve that theme and make it so beautiful? Would make me really happy! The goal is to override the default theme to make it black. Thanks for you future help :)

**Comment by the-simian** [comment]
Just to add to the conversation, https://icons8.com/line-awesome These are a drop-in-replacement for font-awesome that I think looks really great!

**Comment by gotwig** [comment]
i probably can work on the theme when im back from vacation, in July? :D

**Comment by julien-moreau** [comment]
I successfully added svg icons. Now I have to take time to choose them well :)

**Comment by julien-moreau** [comment]
@gotwig I worked on the dark theme, contributions are now open and welcomed when you have time :)

**Comment by julien-moreau** [comment]
@sbfkcel language support has been moved to https://github.com/BabylonJS/Editor/issues/137

**Comment by gotwig** [comment]
@julien-moreau just wondering why u never responded to me on facebook for the last 6 months or something? :/ I wanted to talk to you so often, and now you mentioning me  here. Where can we talk :D?
Greetings, Eddy

**Comment by julien-moreau** [comment]
Answered :)

**Comment by julien-moreau** [comment]
Done :)
Language support has been moved here: https://github.com/BabylonJS/Editor/issues/137
