### ISSUE TITLE
Important v3.1.1 rotation import form from 3ds max bug

### ISSUE THREAD

**Issue by coldestheart** [BabylonJS/Editor#131]
Hello again, after importing from 3ds max scene.babylon with any shapes to babylon editor rotation parameter in Inspector didnt work. then i tried import same scene to bjs editor v2.5.2 rotation works well.
 [Example](https://drive.google.com/file/d/1XY2JviYE4Dm8WdAqMiuu0TRVs28SXEaN/view?usp=sharing)

**Comment by julien-moreau** [comment]
@coldestheart good catch! Thanks for reporting
Has been fixed, was due to the BabylonJS 4.0 update that don't re-integrate rotations in rotation quaternions by default.

Will be available in the release
