### ISSUE TITLE
Update the templated web project to use Webpack instead of SystemJs

### ISSUE THREAD

**Issue by the-simian** [BabylonJS/Editor#135]
Should include:
- webpack 4
- webpack-dev-server
- typescript

**Comment by the-simian** [comment]
@julien-moreau can you assign this to me? I will do this over the weekend.

**Comment by julien-moreau** [comment]
Done :)
Thanks a lot! I think developers will prefer that

**Comment by coldestheart** [comment]
Does this feature already inculded in 3.1.2 alpha3?

**Comment by julien-moreau** [comment]
@coldestheart unfortunately not. Maybe @the-simian can answer when he has planned to begin :)

**Comment by julien-moreau** [comment]
@the-simian,
I started working on that issue but I encounter some problems. Are you a pro of webpack?

**Comment by the-simian** [comment]
Oh man, yes I can help with webpack, I am not sure when I'll have time though. I'm sorry I've let this issue get stale. I have a minimal webpack and typescript setup I've made for a project kind of recently, but I'd need to take a look at this editor's output again and make sure it all fits together.

**Comment by julien-moreau** [comment]
Done with V4 :)
