### ISSUE TITLE
Animation Editor Enchancement

### ISSUE THREAD

**Issue by coldestheart** [BabylonJS/Editor#141]
Hello again! Would be greate if **Animation Editor** start supporting **variables**, what im taking about:
<a href="https://ibb.co/s3Cqzx5"><img src="https://i.ibb.co/BsGBFW4/animation-editor.png" alt="animation-editor" border="0"></a>

**Comment by julien-moreau** [comment]
Thanks!
Will require some time to develop and test but will be available soon :)

**Comment by julien-moreau** [comment]
Will work on it in the next release (3.2.x)
The 3.2.0 is coming soon

**Comment by julien-moreau** [comment]
Done using Graph Editor in V4.
Will be released in few weeks
