### ISSUE TITLE
Some suggestions for the Babylon Editor

### ISSUE THREAD

**Issue by sbfkcel** [BabylonJS/Editor#143]
Some suggestions for the Babylon Editor:
- Add multiple languages
- Multi-screen support
- More beautiful and user-friendly UI (playCanvas, Unity...)
- Scalable Editor

**Comment by julien-moreau** [comment]
Hey @sbfkcel thanks for your suggestions!
I'm keeping the issue opened until I create issues for each subject :)

**Comment by sbfkcel** [comment]
@julien-moreau Good

**Comment by julien-moreau** [comment]
Implemented in V4 of the editor :)
