### ISSUE TITLE
Never ending proccess when saving default scene to GLTF

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#144]
Hi there:

Using the **desktop app** (in its **MS Windows** flavor), when I try to save the default scene as a **GLTF** file (scene+assets), it shows the "Exporting to gltf ..."dialog, but the process never ends.

![image](https://user-images.githubusercontent.com/1760601/61188151-60660e00-a67b-11e9-95de-6a5f3472de9f.png)

![image](https://user-images.githubusercontent.com/1760601/61188155-707ded80-a67b-11e9-9f17-488dfbe2f2d2.png)

Any advice about this?

_P.S. I get the same behavior when I try to export to GLB_
_P.S. Windows 10 Enterprise / v17763.615_

---
UPDATE 2019071401

Tomorrow in the morning I'll be able to test it on MacOSX and let you know.

---
UPDATE 2019071501

Already checked from a MacOSX machine (Mojave / 10.14.1) with same malfunction.

**Comment by julien-moreau** [comment]
Thanks for reporting! I’m fixing ASAP as it worked in the previous version.
Coming back to you ASAP :)

**Comment by julien-moreau** [comment]
@vortice3D it has been reported here: https://github.com/BabylonJS/Babylon.js/issues/6605

**Comment by julien-moreau** [comment]
Fixed! I’m releasing ASAP :)

**Comment by julien-moreau** [comment]
Deployed! You'll get notified while using the editor to download the latest version :)
