### ISSUE TITLE
the build script doesn't include the extensions

### ISSUE THREAD

**Issue by jgsacris** [BabylonJS/Editor#146]
the index.html file requires two scripts: 
./build/src/extensions/extensions.js
./build/src/extensions/post-process/post-processes.js

This scripts are not generated when executing the compile npm script

**Comment by julien-moreau** [comment]
Hi, thanks for the report!
This is weird, my script builds all here :(

Are you working on the master branch?

**Comment by julien-moreau** [comment]
@jgsacris I also tested on OS X and it is working :(

**Comment by julien-moreau** [comment]
@jgsacris any news?

**Comment by jgsacris** [comment]
Sorry for the late reply. After reinstalling Typescript I tried the master
branch and everything is working fine. Most likely there was a problem with
my Typescript configuration.

**Comment by julien-moreau** [comment]
Sound really cool!
Closing the issue then :)
