### ISSUE TITLE
Missing textures while importing draco

### ISSUE THREAD

**Issue by zuffik** [BabylonJS/Editor#148]
Hello guys, I have following problem:
I am using my cloned repo of editor, in file `src/editor/scene/scene-importer.ts` I added a method that is being called on menu item click. It is supposed to load compressed draco file (made from obj) and load textures from mtl file. Both are hosted on local server. The point is that the draco file is being loaded without problem but when I try to load texture from mtl this does not affect material at all.

Thanks in advance
(Please don't judge the code itself, it deserves refactor I am not capable of doing right now)

```typescript
public static async ImportDraco (editor: Editor): Promise<void> {
        $('#draco').click();

        const files: File[] = await new Promise<File[]>(res => {
            $('#draco').on('change', (e: ChangeEvent<HTMLInputElement>) => {
                $('#draco').off('change');
                const files: File[] = [];
                for (let i = 0; i < (e.target.files || []).length; i++) {
                    files.push(e.target.files[i]);
                }
                res(files);
            });
        });
        if (files.length == 0) {
            return;
        }
        const fd = new FormData();
        fd.append('files', files[0]);
        const baseURL = 'http://localhost:5000/';
        BABYLON.DracoCompression.Configuration = {
            decoder: {
                wasmUrl: "https://cdn.jsdelivr.net/gh/google/draco/javascript/draco_decoder.js",
                wasmBinaryUrl: "https://cdn.jsdelivr.net/gh/google/draco/javascript/draco_decoder.wasm",
                fallbackUrl: "https://cdn.jsdelivr.net/gh/google/draco/javascript/draco_wasm_wrapper.js",
            }
        };
        BABYLON.Tools.LoadFile('http://localhost:5000/tree.drc', async function(data: ArrayBuffer) {
            const dracoCompression = new BABYLON.DracoCompression();

            const attributes = {
                // [BABYLON.VertexBuffer.UVKind]: 'uv',
                // [BABYLON.VertexBuffer.NormalKind]: 'normal',
                // [BABYLON.VertexBuffer.ColorKind]: 'color',
                [BABYLON.VertexBuffer.PositionKind]: 'position'
            };

            const scene = editor.core.scene as unknown as BABYLON.Scene;
            const vertexData = await dracoCompression.decodeMeshAsync(data, attributes as any);

            const mesh = new BABYLON.Mesh("dracoMesh", scene);
            const geometry = new BABYLON.Geometry("dracoGeometry", scene, vertexData);
            geometry.applyToMesh(mesh);
            console.log(mesh);
            editor.graph.add({
                data: mesh,
                id: 'tree',
                text: 'tree'
            }, editor.graph.root);

            const mtl = new BABYLON.MTLFileLoader();
            const mtlData = await axios.get('/strazky_tree_bright.mtl', {baseURL});
            mtl.parseMTL(scene, mtlData.data, baseURL);
            mtl.materials[0].backFaceCulling = false;
            mesh.material = mtl.materials[0];
            console.log(mesh.getBoundingInfo());

            scene.addMesh(mesh as any);

        }, undefined, undefined, true);
    }
```
<img width="1679" alt="Snímka obrazovky 2019-10-15 o 21 01 52" src="https://user-images.githubusercontent.com/7671752/66861631-a8a10f00-ef8f-11e9-8021-ee36cdaa0483.png">

<img width="759" alt="Snímka obrazovky 2019-10-15 o 21 01 25" src="https://user-images.githubusercontent.com/7671752/66861572-8b6c4080-ef8f-11e9-95cb-a2c45b02bd00.png">

**Comment by julien-moreau** [comment]
Hey!
I don't know anything about draco for now so I'm getting some informations about and have a look asap! :)

**Comment by julien-moreau** [comment]
Are you sure that the MTLFileLoader has only one material in the .materials array?
Can you share me the material's properties here please?

**Comment by zuffik** [comment]
I am sure in this particular case:

`console.log(mtl.materials.length, mtl.materials, mtl.materials[0]);`

output: 

<img width="956" alt="Snímka obrazovky 2019-10-15 o 22 22 14" src="https://user-images.githubusercontent.com/7671752/66866785-4dc0e500-ef9a-11e9-91e5-684e4f81451d.png">

Full object is here (too large unfortunately :/ )

https://www.dropbox.com/s/aou29hv3b562hmi/material.json?dl=0

**Comment by julien-moreau** [comment]
Still weird, I’m back and I’m having a look
Can you share me the draco files and the link to your fork? Thanks

**Comment by zuffik** [comment]
Hi,
here is my repository: https://gitlab.com/fricka/overhe4d
and here are files: https://www.dropbox.com/s/6j1tw0io4699dsn/babylon-draco.zip?dl=0

there are 3 files:
* `strazky_tree_bright.obj` - original obj file that was later compressed by [draco](https://github.com/google/draco#usage)
* `strazky_tree_bright.mtl` - texture file (mtl files are not compressed by draco)
* `tree.drc` - actual compressed file

**Comment by julien-moreau** [comment]
Can you share also the textures please?

**Comment by zuffik** [comment]
Sure, sorry I forgot: https://www.dropbox.com/s/19j77mv4etrsk9t/babylon-textures.zip?dl=0

**Comment by julien-moreau** [comment]
Are you sure that they are not applied?
Here I can that they are applied but are scaled a lot:
![image](https://user-images.githubusercontent.com/2620127/67623479-e6225980-f825-11e9-8cec-e3ffbc1fc563.png)

**Comment by julien-moreau** [comment]
The obj works, maybe the problem comes from the draco file or the draco reader. You should verify your UV coordinates to be sure they are same

**Comment by zuffik** [comment]
I can achieve this by directly assigning texture to decompressed file (not through mtl file). Otherwise it's just black.
Okay I will check if the file and code is correct and let you know.

**Comment by zuffik** [comment]
Hi, I was working around with this and the code keeps running into this error:

`GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0`

Do you know what can be cause of this situation? I am not familiar with webgl unfortunately.

**Comment by julien-moreau** [comment]
Unfortunately not if I don't have the resources to reproduce. Anyway, I think that the geometries are wrong. I mean that position buffer (or normal or whatever) looks smaller than the indices values

Any news ?

**Comment by julien-moreau** [comment]
@zuffik any news ? :)

**Comment by zuffik** [comment]
Hi, I will dive into this today and tomorrow so I will let you know. Thank you so far

**Comment by zuffik** [comment]
Okay so I checked the materials and everything should be fine (as I think). I ran into following error: 
when I click `View->Materials view` and click the material that just got loaded, there is error in console: `[Error] Not allowed to load local resource: file:///http://localhost:5000//textura_strazky_Update.png`

**Comment by julien-moreau** [comment]
The error comes from the editor manages only files and not URLs
What are you trying to do exactly with the editoor?

**Comment by zuffik** [comment]
As I said: just clicked on material (loaded from mtl file) in "Materials view" and this came up. 
Maybe it's just some side effect but I was wondering if there may be some causality between this error and lack of textures.

**Comment by julien-moreau** [comment]
Done, Editor v4 now uses local file system for files :)
