### ISSUE TITLE
Add orbit-style editor navigation

### ISSUE THREAD

**Issue by andrewpeterprifer** [BabylonJS/Editor#149]
Right now there are two navigation options in the editor: "Free" and "Arc Rotate", which allow you to look around, but not to orbit around the center (or a given object), which is how most DCCs and scene editors work from Maya to Unity.

I think an orbit-style navigation scheme would make the editor much easier to use.

**Comment by julien-moreau** [comment]
Hey thanks for this feedback!
I agree that the editor should implement its own camera to fit the standards.

For instance you can use the arc rotate camera and press « f » once the mouse is in the preview panel to focus an object and rotate around.
Is it working for you?

**Comment by andrewpeterprifer** [comment]
Hey, thanks! Didn't realize you could do that.
