### ISSUE TITLE
Editor will stop working after changing texture on object.

### ISSUE THREAD

**Issue by rohapa** [BabylonJS/Editor#15]
Editor will stop working after changing texture on object. Issue occurs right after clicking Browse

**Comment by julien-moreau** [comment]
Thanks for reporting this issue!
Are you using the "develop" branch of the editor ? Which kind of texture ? Cube texture ? On which material type ? Standard Material ?
Thanks!

**Comment by julien-moreau** [comment]
I committed a fix in the "develop" branch, can you test locally or are you using the editor.babylonjs.com website ?
