### ISSUE TITLE
NPM dependency for babylonjs-editor version 3.1.3 causes issues in compiling

### ISSUE THREAD

**Issue by QANewb** [BabylonJS/Editor#153]
When I tried the first tutorial on Babylon JS, I downloaded the latest version of the Editor and Did the tutorial.
Upon exporting the project template, the generated package.json contains v3.1.3 of babylonjs-editor.
Doing yarn install on this did not work, I got like 261 errors.
Reduced the version to 3.1.2 and all worked fine.
Not sure if this is only on my machine but the DEV should definitely take a look at this.

![image](https://user-images.githubusercontent.com/22387174/67620003-e95c1c00-f80a-11e9-8d05-acad772667b9.png)

**Comment by julien-moreau** [comment]
Ouch! Can you tell me if you have BabylonJS dependencies in the node_modules/babylonjs-editor/node_modules folder ?
If yes, I can fix easily. Else, I’ll have to reproduce first :)

Thanks for reporting!

**Comment by julien-moreau** [comment]
Reproduced, fixing ASAP!

**Comment by julien-moreau** [comment]
Can you try the version "3.2.0-beta.4" and tell me if it works? thanks :)

**Comment by QANewb** [comment]
@julien-moreau 
I am sorry for the late reply, I don't often check this account or the mail associated.
The problems seems to be fixed, and the issue can be closed.
![image](https://user-images.githubusercontent.com/22387174/69757385-8b05be80-1165-11ea-8ce7-34fe12bb2ac0.png)
