### ISSUE TITLE
GLB assets have faces flipped when export

### ISSUE THREAD

**Issue by jpionnie** [BabylonJS/Editor#159]
Hi,
With the latest version of the editor it seems that export flip the faces of .glb file.

Export with babylon exporter:
![Screen_flip_normal_01](https://user-images.githubusercontent.com/17312123/68120040-9cf89680-ff04-11e9-8a4f-9e7cd09bae88.png)

Import in editor :
![Screen_flip_normal_03](https://user-images.githubusercontent.com/17312123/68120205-037db480-ff05-11e9-9abc-717e29a196d4.png)

Export :
![Screen_flip_normal_02](https://user-images.githubusercontent.com/17312123/68120043-9ec25a00-ff04-11e9-9e7b-19a922215840.png)

**Comment by julien-moreau** [comment]
Hey thanks for reporting! I’m checking!
Maybe it is just due to the coordinates system. As a developer, can you put your scene as right handed system ?

**Comment by julien-moreau** [comment]
Also, for your export, have you chosen .babylon or .gltf/glb ?

**Comment by julien-moreau** [comment]
I don't reproduce when using GLB/GLTF as export but only when I export to .babylon
I'm trying to fix now

**Comment by julien-moreau** [comment]
@jpionnie do you still reproduce when choosing GLTF or GLB as export format?

**Comment by jpionnie** [comment]
@julien-moreau On my last check it's seems ok for GLB and glTF, my bad. Thx for your reactivity.

**Comment by julien-moreau** [comment]
Good to know!
After analysis, I think the only good fix is to configure the scene to use right handed system. will let you know once fixed for the .babylon format :)

**Comment by julien-moreau** [comment]
Done :)
