### ISSUE TITLE
Docking support

### ISSUE THREAD

**Issue by amerkoleci** [BabylonJS/Editor#16]
What about integrating golden layout?
https://www.golden-layout.com

Its licensed under MIT license.

**Comment by julien-moreau** [comment]
Looks awesome !! I'll plan to use it, I see some cases really interesting
I keep this issue open until I begin the work
Thanks for sharing :)

**Comment by julien-moreau** [comment]
Do you plan to contribute to the editor ?

**Comment by amerkoleci** [comment]
Nah, just digging around various projects, I'm using usually C++ or C# (.NET).

**Comment by julien-moreau** [comment]
Good, I close the issue but I'm happy to meet golden layout :)
Thanks!
