### ISSUE TITLE
Click without arrow tip

### ISSUE THREAD

**Issue by JACKJKL** [BabylonJS/Editor#163]
![pointArrow](https://user-images.githubusercontent.com/20449848/70034110-a4868a80-15eb-11ea-82d3-45b75175b1d2.png)

**Comment by julien-moreau** [comment]
Hey thanks for reporting :)
Can you elaborate a little bit? Thanks :)

**Comment by julien-moreau** [comment]
@JACKJKL any news ? Thanks :)

**Comment by JACKJKL** [comment]
> @JACKJKL any news ? Thanks :)

Cameras and lights cannot be edited in the scene like their entities

**Comment by julien-moreau** [comment]
@JACKJKL looks like the BabylonJS gizmos can't modifie the transforms of light and cameras.
Maybe @TrevorDev can help :)

Thanks

**Comment by julien-moreau** [comment]
Available in editor V4 :)
