### ISSUE TITLE
Add Camera Gizmo

### ISSUE THREAD

**Issue by JACKJKL** [BabylonJS/Editor#164]
![1](https://user-images.githubusercontent.com/20449848/70296249-d9315680-1824-11ea-8e78-98401ece1de4.png)

**Comment by julien-moreau** [comment]
Would like to do the same for lights. Adding more gizmos in the todo list :)

**Comment by julien-moreau** [comment]
Done! Thanks to the awesome work of Cedric :) (https://forum.babylonjs.com/u/Cedric)
