### ISSUE TITLE
Export folders and script for use on embedded websites (Angular, React Vue etc)

### ISSUE THREAD

**Issue by MisterLight** [BabylonJS/Editor#168]
We are working on a website made in Angular, where the main part (or the fun part) will be a game embedded with a canvas inside the main html alongside other components:  sidebar, modals etc.

We are in a alpha phase, and our first approach will be use the standalone babylon.js library as is, create some components for handle de canvas and put inside the code that work with the babylon library and move on.

Right now, we have a background with Unity and we thought on give a chance the babylon editor because we are more comfortable creating a game using the help of a editor for speed up the process. The problem here come to the way the editor export the scenes and scripts saving it in a .editorproject file.

What we will need is a way to create a game in the editor and export it to our angular project in the way that we can organize the exported typescript and assets of the game
 
On this way we can use it in combination with the non-game website components and we might split up our team one side for the game itself and the other for website issue.

I think this will be a really improve, because many of the 3D or graphical content on website usually 
is a part of a website and use a editor for handle this specific thing would be very useful and great

**Comment by julien-moreau** [comment]
Hey! Thanks for this great issue!
I'm currently working on exporting to be compliant with the ES6 version of BabylonJS.

Today available:
* export final assets separatly
* module named "babylonjs-editor-es6"

Today not available:
* export typescript files (custom scripts) in ES6 format

What I think is: the website should import itself the generated project scripts (typescript files exported from the editor) and call the "babylonjs-editor" module to ApplyExtensions like you have in the Project Template of the editor. Do you confirm that kind of use ?

**Comment by julien-moreau** [comment]
Done with Editor V4 :)
The generated project (using webpack) can be packed and used externally or include libs
