### ISSUE TITLE
Rotation widget not changing Transform in Inspector

### ISSUE THREAD

**Issue by Sparcks** [BabylonJS/Editor#169]
I'm using the Windows Editor, but seems to be the same in the Web Editor.
When I use the rotation widget and rotate my object, it does not get updated in the properties inspector. The Rotation property in Transforms stays the same.

Is this normal or am I doing something wrong?

Also a bit of feedback: Eulers would be more easy to use than radians, but this can be fixed through code anyway. And if you select an object that cannot be moved with a widget, you still have selected the previous movable object. There should be a deselect when you click nothing in the Graph tab or the widget should disappear when you select an object that doesn't have widget options (like camera or light).

Thanks in advance.

**Comment by julien-moreau** [comment]
Thanks for reporting!
You are right this is not the expected behavior. I'm fixing it asap.
I know that the widget modifies the rotation quaternion and not the rotation vector. The edition tool displays the properties of the rotation vector. In all cases the display must be updated.

Good catches.

I'm fixing all of that ASAP :)

**Comment by Sparcks** [comment]
> Thanks for reporting!
> You are right this is not the expected behavior. I'm fixing it asap.
> I know that the widget modifies the rotation quaternion and not the rotation vector. The edition tool displays the properties of the rotation vector. In all cases the display must be updated.
> 
> Good catches.
> 
> I'm fixing all of that ASAP :)

Alright, that was fast! :-D 

Radians was indeed not the correct math term, because it was 1.6 not 6.23... My bad, I confused myself again. Vector it is.
Anyway, thanks for looking into this!

**Comment by julien-moreau** [comment]
Fixed! Deploying asap :)

**Comment by julien-moreau** [comment]
Finally fixed!
