### ISSUE TITLE
Duplicate object get same scripts attached after being duplicated

### ISSUE THREAD

**Issue by Sparcks** [BabylonJS/Editor#170]
I found an issue with the script attachments. 

Scenario: I Create an object, in this case a plane. After that, I make a clone/duplicate object of it with a different name. I even create a different material for it and assign it to that second object. 
Now when I attach a script to my first object, it automatically gets attached to that object that was duplicated. 

It seems that the duplicated object gets like the same ID or something as the first object and therefor links the script to it too?
I duplicated the object, because I just needed another plane with the same rotation.

Thanks in advance.

**Comment by julien-moreau** [comment]
@Sparcks good catch too, I have a solution.
Cloning an object means you want a perfect clone of it. I think the editor should ask the user if it should also clone the object's metadata (scripts, graphs, etc.).

What do you thing about that ?

**Comment by Sparcks** [comment]
> Cloning an object means you want a perfect clone of it.

Ah ok, I understand. 

>  think the editor should ask the user if it should also clone the object's metadata (scripts, graphs, etc.).

That could be a solution indeed or the option 'Copy' or 'Duplicate' which does just that, without the extra popup?

**Comment by julien-moreau** [comment]
Good!
So if I understand:
* Copy (or Clone): creates a perfect copy
* Duplicate: creates a copy of the mesh by doesn't copies the metadata

Am I right ?

**Comment by julien-moreau** [comment]
Done in V4 :)
