### ISSUE TITLE
can't build the editor

### ISSUE THREAD

**Issue by somerandomguy83** [BabylonJS/Editor#171]
`
C:\node\BabylonJS_editor>node ./script/install.js

-------------------------------------------------------------
cd photoshop-extension && npm i && cd ..
-------------------------------------------------------------

Installed:  cd photoshop-extension && npm i && cd ..
added 45 packages from 33 contributors and audited 77 packages in 1.306s
found 0 vulnerabilities

-------------------------------------------------------------
cd vscode-extension && npm i && cd ..
-------------------------------------------------------------

Installed:  cd vscode-extension && npm i && cd ..

> babylonjs-editor@3.2.0 postinstall C:\node\BabylonJS_editor\vscode-extension
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.28.0
Found minimal version that qualifies engine range: 1.28.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

added 593 packages from 623 contributors and audited 5683 packages in 16.391s
found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

-------------------------------------------------------------
npm i
-------------------------------------------------------------

Installed:  npm i

> core-js@2.6.10 postinstall C:\node\BabylonJS_editor\node_modules\core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> electron@5.0.1 postinstall C:\node\BabylonJS_editor\node_modules\electron
> node install.js

Downloading tmp-9000-1-SHASUMS256.txt-5.0.1
[============================================>] 100.0% of 4.74 kB (4.74 kB/s)
added 678 packages from 446 contributors and audited 2236 packages in 75.863s
found 16 vulnerabilities (9 low, 1 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\node\BabylonJS_editor>npm run build

> babylonjs-editor@3.2.0 build C:\node\BabylonJS_editor
> npm run compile && npm run compile-electron && npm run compile-photoshop && npm run build-vscode-extension && npm run bundle

> babylonjs-editor@3.2.0 compile C:\node\BabylonJS_editor
> tsc -p .

src/extensions/behavior/graph.ts:319:13 - error TS2740: Type 'typeof SubGraph' is missing the following properties from type 'LGraphNode': title, type, size, graph, and 66 more.

319             'graph/subgraph': SubGraph,
                ~~~~~~~~~~~~~~~~

src/extensions/behavior/graph.ts:320:13 - error TS2740: Type 'typeof GraphInput' is missing the following properties from type 'LGraphNode': title, type, size, graph, and 66 more.

320             'graph/input': GraphInput,
                ~~~~~~~~~~~~~

src/extensions/behavior/graph.ts:321:13 - error TS2740: Type 'typeof GraphOutput' is missing the following properties from type 'LGraphNode': title, type, size, graph, and 66 more.

321             'graph/output': GraphOutput
                ~~~~~~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:3:31 - error TS2507: Type 'LGraphNode' is not a constructor function type.

3 export class SubGraph extends LiteGraph.Nodes.Subgraph {
                                ~~~~~~~~~~~~~~~~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:15:33 - error TS2507: Type 'LGraphNode' is not a constructor function type.

15 export class GraphInput extends LiteGraph.Nodes.GraphInput {
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:27:36 - error TS2339: Property 'addWidget' does not exist on type 'GraphInput'.

27         this['name_widget'] = this.addWidget('text', 'Name', this.properties.name, (v) => {
                                      ~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:27:67 - error TS2339: Property 'properties' does not exist on type 'GraphInput'.

27         this['name_widget'] = this.addWidget('text', 'Name', this.properties.name, (v) => {
                                                                     ~~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:31:36 - error TS2339: Property 'addWidget' does not exist on type 'GraphInput'.

31         this['type_widget'] = this.addWidget('combo', 'Type', this.properties.type, (v) => {
                                      ~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:31:68 - error TS2339: Property 'properties' does not exist on type 'GraphInput'.

31         this['type_widget'] = this.addWidget('combo', 'Type', this.properties.type, (v) => {
                                                                      ~~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:49:34 - error TS2507: Type 'LGraphNode' is not a constructor function type.

49 export class GraphOutput extends LiteGraph.Nodes.GraphOutput {
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:61:36 - error TS2339: Property 'addWidget' does not exist on type 'GraphOutput'.

61         this['name_widget'] = this.addWidget('text', 'Name', this.properties.name, (v) => {
                                      ~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:61:67 - error TS2339: Property 'properties' does not exist on type 'GraphOutput'.

61         this['name_widget'] = this.addWidget('text', 'Name', this.properties.name, (v) => {
                                                                     ~~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:65:36 - error TS2339: Property 'addWidget' does not exist on type 'GraphOutput'.

65         this['type_widget'] = this.addWidget('combo', 'Type', this.properties.type, (v) => {
                                      ~~~~~~~~~

src/extensions/behavior/nodes/sub-graph.ts:65:68 - error TS2339: Property 'properties' does not exist on type 'GraphOutput'.

65         this['type_widget'] = this.addWidget('combo', 'Type', this.properties.type, (v) => {
                                                                      ~~~~~~~~~~

src/tools/graph-behavior/graph-node-tool.ts:42:34 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

42                object instanceof LiteGraph.Nodes.Subgraph ||
                                    ~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph-node-tool.ts:43:34 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

43                object instanceof LiteGraph.Nodes.GraphInput ||
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph-node-tool.ts:44:34 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

44                object instanceof LiteGraph.Nodes.GraphOutput;
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph-node-tool.ts:69:36 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

69         } else if (node instanceof LiteGraph.Nodes.Subgraph) {
                                      ~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph-node-tool.ts:71:36 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

71         } else if (node instanceof LiteGraph.Nodes.GraphInput || node instanceof LiteGraph.Nodes.GraphOutput) {
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph-node-tool.ts:71:82 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

71         } else if (node instanceof LiteGraph.Nodes.GraphInput || node instanceof LiteGraph.Nodes.GraphOutput) {
                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph.ts:741:32 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

741             if (!(n instanceof LiteGraph.Nodes.Subgraph))
                                   ~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph.ts:754:30 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

754             if (n instanceof LiteGraph.Nodes.Subgraph)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~

src/tools/graph-behavior/graph.ts:769:30 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

769             if (n instanceof LiteGraph.Nodes.Subgraph)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~


Found 23 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! babylonjs-editor@3.2.0 compile: `tsc -p .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the babylonjs-editor@3.2.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Serge\AppData\Roaming\npm-cache\_logs\2020-01-10T06_12_27_827Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! babylonjs-editor@3.2.0 build: `npm run compile && npm run compile-electron && npm run compile-photoshop && npm run build-vscode-extension && npm run bundle`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the babylonjs-editor@3.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Serge\AppData\Roaming\npm-cache\_logs\2020-01-10T06_12_27_852Z-debug.log

C:\node\BabylonJS_editor>`

**Comment by julien-moreau** [comment]
Fixed! The fix is available on the master branch :)
