### ISSUE TITLE
[Linux app] Segmentation fault

### ISSUE THREAD

**Issue by SebastienTainon** [BabylonJS/Editor#172]
Hello,
I've downloaded the Linux editor app (.zip) file and unzipped it. When I use the app, it sometimes randomly closes and then I have this message in the console:

```./babylonjs-editor
[1]    19577 segmentation fault (core dumped)  ./babylonjs-editor
```
It's not really consistent, sometimes it happens when I create a project, sometimes when I save it, etc... I can use it for a few minutes or sometimes even a few seconds and then it crashes with always this same error, so practically it's not usable currently.

**Comment by julien-moreau** [comment]
Ouch!
As a linux user, are you able to clone the repo and build it yourself ?
You can start from the branch "feature/es6"

**Comment by julien-moreau** [comment]
I unfortunately don't have linux working here, my VMs crash on startup :(

**Comment by SebastienTainon** [comment]
@julien-moreau I've checked out branche `feature/es6`, installed dependencies, built and I now have the 3.2.1-beta4 package. I opened it and a few seconds later... same error :(
```
BabylonEditor/electron-packages/linux-unpacked  feature/es6 ./babylonjs-editor 
[1]    17186 segmentation fault (core dumped)  ./babylonjs-editor
```

**Comment by julien-moreau** [comment]
Aïe aïe aïe...
To focus on the problem (I suggest a problem when writing/reading files) can you open the editor and play with it without saving ? If the crash still happens, maybe the problem comes from the version of electron

**Comment by SebastienTainon** [comment]
I think I know what's going on... I naively thought we could use the window menus:

![Image](https://zupimages.net/up/20/14/pjj5.png)

But when I click them (File for example), it systematically triggers the segmentation fault so I'm wondering if they are of any use at all. Apart from that, I used the editor for 30 mins and managed to create and export a scene and a project without any segmentation fault, so maybe previously I had just used these menus and that's what triggered the errors.

**Comment by julien-moreau** [comment]
Yeaaaaah good to know!
These menus should not appear as I have set them « hidden ». Will fix that, so I keep the issue opened :)
Thanks again for you help

**Comment by neytjs** [comment]
Yes, the editor also crashes for me whenever I accidentally click those default Electron app menu options. I am running it on Linux Mint. I also get that "Segmentation fault (core dumped)" message in the terminal. I have written two Electron apps that I use regularly and I have never seen this type of crash before trying this editor. Hope this info helps. :)

**Comment by julien-moreau** [comment]
Hi sure,
At the moment I haven’t found why the menu bar is still visible as I asked to hide it :(
Anyway my fix will be, just to avoid crashes, to add an empty menu bar

**Comment by neytjs** [comment]
I read on stackoverflow about some issues with hiding menus depending on which version of Electron is being used. Older versions of Electron called the setMenu() method with null passed in as an argument, while newer versions call the removeMenu() method. So I think that placing either this.Window.setMenu(null) or this.Window.removeMenu() in the main.ts file should make it hidden.

**Comment by julien-moreau** [comment]
Thanks for the feedback. It has been fixed in the v4 of the editor.
Are you interested to be a beta tester ?

**Comment by neytjs** [comment]
Yes, I will try to provide some feedback. I downloaded your latest version (4.0.0-beta.0). When I ran npm run build I am getting the following error in my terminal:

Building Electron...
  • electron-builder  version=22.5.1 os=4.15.0-54-generic
(node:2928) UnhandledPromiseRejectionWarning: /home/nate/Downloads/Editor-4.0.0-beta.0/node_modules/app-builder-lib/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nate/Downloads/Editor-4.0.0-beta.0/node_modules/app-builder-lib/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
(node:2928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

________________________________

**Comment by julien-moreau** [comment]
Looks like it is related to the NodeJS version
What version are you using ? I suggest to use at least the V12

**Comment by neytjs** [comment]
Thanks, that was my problem. I was still using version 8.10. I am now using nvm to run newer versions of node. I have now started up your editor and checked it out a little. It definitely looks a lot nicer than the previous version I tried, although I do not have much time to test it right now. I will test a few more things later in the week or next week and see if I find any issues to report.

________________________________

**Comment by julien-moreau** [comment]
Thanks a lot! Would help me a lot :)
I’m going to work on the tutorials for the V4, the documentation will be available soon

**Comment by neytjs** [comment]
I have been testing a little bit. I have encountered some erratic behavior regarding importing meshes, specifically Blender projects that were converted into .babylon files. Sometimes after dropping in the .babylon files and adding the mesh to the scene I would not see the textures. Other times I would. It seemed to be at random. I also had a mesh that looked fine in Blender and also inside my own personal .babylon importer project, but in the editor all the cubes that made it up were bunched together in a strange way (hard to explain, but it looked like they were all at the position 0, 0, 0).

________________________________
