### ISSUE TITLE
Desktop version download link is not clearly identified.

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#174]
Hi there:

Following the Readme.md explanation is not evident (at least for me) that indeed exists a **desktop version**, whose link is located under [Docs/Resources/Resource1](https://doc.babylonjs.com/resources/getting_started).

I think that this link must be shared in a more prominent way, particularly by regards of what you can read in the mentioned **getting_started** page, namely: "_It is highly recommended using the desktop app as you'll get access to the local file system to save your projects._"

Best regards.

**Comment by julien-moreau** [comment]
You are totally right
The version 4.0.0 of the editor is being developed and does not support the web version anymore. That means editor.babylonjs.com will be just an home page to download the editor. The documentation will be modified as well

The development is focused on the 4.0.0 to release it ASAP :)

Thanks for reporting :)
