### ISSUE TITLE
[MacOS] Double-click scene.editorproject does not open

### ISSUE THREAD

**Issue by Corysia** [BabylonJS/Editor#176]
Following the instructions at https://doc.babylonjs.com/resources/explaining_workflow#2-iterate-on-that-scene when double-clicking on my scene.editorproject, the saved project is not opened.  Instead, a new example project is loaded in to the editor.

Saving the project works as expected.

Work around
After re-opening the editor, choose `Project->Import Project` to load the saved project.

Tested in desktop version of both Mac and Windows.  Project opened correctly in Windows.  I saw the above behavior with Mac.

**Comment by julien-moreau** [comment]
Thanks for reporting! Found the bug few days ago and has been fixed :)

**Comment by julien-moreau** [comment]
If you are interested to be a beta tester of the V4, I’ll close the issue, else, will not close until it has been released in the V3

**Comment by julien-moreau** [comment]
Finally done!
