### ISSUE TITLE
Add Link To Attached Script in Inspector For Nodes

### ISSUE THREAD

**Issue by Corysia** [BabylonJS/Editor#177]
Experimenting with attaching a script to an object, I noticed I couldn't easily see the object had a script.  When opening the script, I could see it was attached to an object from the left-hand pane of the editor.  It would be nice to see and access scripts from the object via the inspector similar to how Unity and Unreal offer.

**Comment by julien-moreau** [comment]
Hey ! Thanks for this feedback, I’m adding the link ASAP !

The V4 of the editor is being developed and should be released in few weeks. As this is issue is not a bug that breaks projects, i suggest to focus on the V4 and provide you a more rich exprerience on it.

Are you interested to be a beta tester of the V4 ?

**Comment by Corysia** [comment]
Yes, I would be very interested in trying out v4 and seeing what I can do with it!

**Comment by julien-moreau** [comment]
Good! Are you on the babylonjs forum?

**Comment by Corysia** [comment]
Yes I am, same username.

**Comment by julien-moreau** [comment]
Done, added a button to open the file directly from the inspector.
Also added (hidden by default) a preview section of the script like Unity does
