### ISSUE TITLE
[MacOS] Frequent crashes when adding assets to Texture Viewer

### ISSUE THREAD

**Issue by DanKomorny** [BabylonJS/Editor#178]
**What:** Experiencing sudden editor crashes after adding *.PNG files in the cube map splicer window.

**How:** New Project > Texture Viewer > Add > Pure Cube Texture

**Where:** 
  Catalina 10.15.4
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2,3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

[behavior recording.zip](https://github.com/BabylonJS/Editor/files/4681583/behavior.recording.zip)

**Comment by julien-moreau** [comment]
Ouch! Thanks for reporting, I’m fixing ASAP !
And thanks for this well description, helps me :)

**Comment by DanKomorny** [comment]
Thanks! Worked for years in professional dev teams in QA role so used to high standards of bug reporting :)

**Comment by Corysia** [comment]
Agreed!  Great report.  I"m going to have to step up my game, it seems!  =)

**Comment by julien-moreau** [comment]
I don't reproduce here after (at least) 20 tries.
And because it crashes, we can't see the logs :(

Still looking for the crashes

**Comment by DanKomorny** [comment]
Not sure if it'll help you but adding the system crash log as well:

[MacOS crash log.zip](https://github.com/BabylonJS/Editor/files/4717565/MacOS.crash.log.zip)

**Comment by julien-moreau** [comment]
I'm on it

**Comment by julien-moreau** [comment]
Hey @DanKomorny 
I just re-developed the feature in the editor v4.0.0-beta.1 (which can be downloaded here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta)

Can you test it on your mac and tell me if it still crashes ? Thanks !! :)

To add a new pure cube texture, simply go to the "Textures" tab in assets and click "Add... -> Pure Cube Texture". The same dialog as V3 will open

**Comment by julien-moreau** [comment]
@DanKomorny any news?
I still don't reproduce on my Mac :(

**Comment by julien-moreau** [comment]
@DanKomorny still no news? :(
