### ISSUE TITLE
Cannot add SpotLight

### ISSUE THREAD

**Issue by ArosPrince** [BabylonJS/Editor#192]
No matter what I do, I just cannot add SpotLight in both desktop application and the web app. PointLight and DirectionLights are fine, but adding SpotLight simply does nothing.

**Comment by julien-moreau** [comment]
Ouch!

I had the same issue on the Editor v4.0.0-beta and it has been fixed.
For information, have you began a project with the existing Editor (v3) ? The Editor v4 is coming soon in its final version and provides more mordern tools with more stability to create/edit and export scenes. My goal is to stop all starting developments that use the Editor v3 as the v4 comes with a lot of better features.

If not, and you are interested in, I suggest that you start using the Editor v4.0.0-beta which will be released in few weeks. All beta downloads are available here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta

And the documentation (still WIP) is available here: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

**Comment by ArosPrince** [comment]
OK, thanks.

I installed v4.0.0-beta.2. Now I can add spot light, but I cannot change it's position. The only options for it are shadows. Also the move tool doesn't seem to work with lights, but just mashes.

**Comment by julien-moreau** [comment]
Hey @ArosPrince the beta.3 has been released and is available here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta

The lights can now be moved using the Editor's inspector or using the Gizmos
Don't hesitate to open new issues if you encounter bugs :)
