### ISSUE TITLE
Error Showing Up When Installing Local Editor

### ISSUE THREAD

**Issue by MegsTan** [BabylonJS/Editor#194]
I followed this instruction: https://github.com/BabylonJS/Editor/blob/master/README.md
I have npm installed and when I type in "npm run build", I get the error : https://pasteboard.co/JiMJTfA.png

**Comment by julien-moreau** [comment]
Hey @MegsTan and welcome!
For the build, I suggest that you use the branch "release/4.0.0" that contains the version 4 of the Editor. It'll be released in few weeks and is radically different from the one (v3) on master.

I highly recommand that you start from the v4 :)

Let me know if you encounter any installation/build problem with the "release/4.0.0" branch, I'll fix it ASAP!

**Comment by MegsTan** [comment]
Thank you I'll check this out, I'm new to BabylonJS, I am currently using Unity and Unreal, however, not good for the web because mainly the game size and we are trying to integrate the game with react so BabylonJS is a good option for us. Thank you will keep you posted

**Comment by MegsTan** [comment]
I saw the standalone editor THIS IS AMAZING!!!!!!!! This is what we were looking for. You guys rock!!!!!!!!! We will keep supporting the editor. I love you guys!!!!!!!!!!!!!
