### ISSUE TITLE
I can't build the Editor

### ISSUE THREAD

**Issue by mohammedgqudah** [BabylonJS/Editor#195]
Hey,  I'm trying to install the editor on `Linux` I'v cloned this repo and I ran `node ./script/install.js` however when I build(`npm run build`) it it gives me an error:

```
> babylonjs-editor@3.2.0 build /home/mohammedgqudah/Desktop/projects2020/Editor
> npm run compile && npm run compile-electron && npm run compile-photoshop && npm run build-vscode-extension && npm run bundle


> babylonjs-editor@3.2.0 compile /home/mohammedgqudah/Desktop/projects2020/Editor
> tsc -p .


> babylonjs-editor@3.2.0 compile-electron /home/mohammedgqudah/Desktop/projects2020/Editor
> tsc -p ./electron

electron/routes/storage.ts:133:21 - error TS2345: Argument of type '{ title: any; defaultPath: any; properties: any[]; }' is not assignable to parameter of type 'BrowserWindow'.
  Object literal may only specify known properties, and 'title' does not exist in type 'BrowserWindow'.

133                     title: ctx.query && ctx.query.title ? ctx.query.title : undefined,
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

electron/routes/storage.ts:150:21 - error TS2345: Argument of type '{ title: any; defaultPath: any; properties: string[]; }' is not assignable to parameter of type 'BrowserWindow'.
  Object literal may only specify known properties, and 'title' does not exist in type 'BrowserWindow'.

150                     title: ctx.query && ctx.query.title ? ctx.query.title : undefined
```

Am I missing something?

**Comment by julien-moreau** [comment]
Hey @mohammedgqudah welcome!!
Sorry for the delay!

The master branch of the Editor repository contains the version 3. I suggest that you start using the version 4 as it'll be released in few weeks. The v4 is available in the branch "release/4.0.0".

The v4 has been made from scratch to be more modern and more powerful.
Also, it would help me a lot if you can try the latest build I made for Linux (just to see if it works on a real Linux machine): https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta
I have tested only on a VM.

I'm not familiar with the Linux community so I don't really know what linux users are waiting. I mean, does an AppImage enough and what you are looking for? Do you prefer .deb files?

Thanks for your answer :)

**Comment by mohammedgqudah** [comment]
Thanks @julien-moreau I got it running using the AppImage(yes AppImages are good for linux)! I love this update so much its much better than the browser version GJ :) 

I know it's beta but I wanna make sure this is expected for now:
![image](https://user-images.githubusercontent.com/26502088/88430387-0b69e580-ce01-11ea-982d-7b6d09e69adf.png)

the material option is gone(even when you right click on the ground from the graph list)

and I wanna say something, I'v been using BabylonJS for a while now I'm loving it you guys are AMAZING!

**Comment by julien-moreau** [comment]
Hey @mohammedgqudah :)
This is expected as there is no bug, the field doesn't exists ^^. To assign a material you can drag'n'drop a material from the asset's panel on a mesh in the preview.
Anyway, I'm adding it as it makes sense to have this field here :)

**Comment by julien-moreau** [comment]
@mohammedgqudah just pushed on release/4.0.0, you can pull and the field now exists for meshes :)
