### ISSUE TITLE
Blender rigify unable to recognized by babylonjs editor after exporting as gltf "character animation"

### ISSUE THREAD

**Issue by rvnosa** [BabylonJS/Editor#197]
Hi,
 I am trying to export an animated character using blender rigify to babylon js edtor using gltf file format. When imported and drag to the preview, I can see the animation playing in the editor, I'm trying to play the animation via code however I found out that the object is converted into transform node instead of mesh. Do you have any suggestions on how to fix it.

**Comment by julien-moreau** [comment]
Hey @rvnosa and welcome! :)
Thanks for reporting that. To help me debugging, is that possible to share the 3d animated model or at least a minimal-repro of a 3d model?
Thanks a lot

**Comment by rvnosa** [comment]
---------- Forwarded message ---------
From: Chad VN <rver.nosa@gmail.com>
Date: Fri, Jul 24, 2020 at 11:19 PM
Subject: Re: Delivery Status Notification (Failure)
To: Mail Delivery Subsystem <mailer-daemon@googlemail.com>


I zipped in rar file

**Comment by julien-moreau** [comment]
Hi @rvnosa 
It looks your message failed, I can't see any file to download :(

**Comment by rvnosa** [comment]
where can I send the gltf file? it is 3mb

**Comment by julien-moreau** [comment]
Can you try one driver or google drive and share a link to the file ?

**Comment by rvnosa** [comment]
you can get the file  at https://drive.google.com/file/d/1EcHlJXdD4_3moKKqK4qFoSUC_nt4nUlZ/view?usp=sharing

**Comment by julien-moreau** [comment]
@rvnosa thanks for sharing,
Just asked for an access, I think you received a mail :)

**Comment by julien-moreau** [comment]
Hey @rvnosa 
Just tried the model. The model is empty on its right is that normal? I have to same result in the Editor and in the Babylon.JS Sandbox (https://sandbox.babylonjs.com/). So this more a problem with the model or (i doubt) a problem with the GLTF loader of Babylon.JS itself.

I attached a script to the root mesh "__root__" and it is still a "Mesh" class (see the informations in the console):
![image](https://user-images.githubusercontent.com/2620127/88699897-30fc3500-d108-11ea-9857-c3bfdedd8d0d.png)

Where have you attached the script exactly? On the root mesh too? Also I can see that the mesh is composed of multiple meshes that share the same skeleton. The Editor doesn't merge these meshes, it keeps the mesh as it is.

**Comment by rvnosa** [comment]
Good day, sorry for late reply, yes the mesh is half is not there, yes the
mesh are composited of meshes same what I experienced

**Comment by rvnosa** [comment]
I tried a manual bone setup and if I am right the total of bones I did is
20, still there is error when exporting to .babylon file

**Comment by julien-moreau** [comment]
Would it be possible that you show me each step and focus on the errors you have ? For example using a video to show me what you are doing. I'm unfortunately not sure to understand how to reproduce :(

**Comment by julien-moreau** [comment]
@rvnosa any news?

**Comment by rvnosa** [comment]
I stop converting it, loose hope on rigify to babylon, but I did a manual
bone rig setup and export as gltf and it is successful 😆👍

**Comment by julien-moreau** [comment]
Yeaaaaah that rox! Closing the issue then :)
