### ISSUE TITLE
When dragging a pin into an empty space in the graph editor should give you a context menu

### ISSUE THREAD

**Issue by MegsTan** [BabylonJS/Editor#199]
Hi @julien-moreau ,

The graph editor is really great just lacking one important feature where if you drag a pin into an empty space in the graph it should give you a context menu that only applies to that pin or a more specific option than just right-clicking into the empty space.

![CC](https://user-images.githubusercontent.com/44461836/88458557-7e3a9580-cec1-11ea-8b6c-76ae655bfde3.png)

![AA](https://user-images.githubusercontent.com/44461836/88458563-872b6700-cec1-11ea-9c4a-201a60011c59.png)

![BB](https://user-images.githubusercontent.com/44461836/88458567-8b578480-cec1-11ea-914f-9e2064b7b41a.png)

**Comment by julien-moreau** [comment]
Hey @MegsTan 
I 100% agree with you. I tried to add this feature but the Graph Editor depends on a thrid-party library named "litegraph.js" (https://github.com/jagenjo/litegraph.js) that did not allow me to do that. I still have to contribute/create an issue on that library.

Depending on the reactivity of the library's maintainers, I keep this issue opened and will tell you once done :)

**Comment by MegsTan** [comment]
Hi @julien-moreau 

Okay sounds good. Thanks!

**Comment by julien-moreau** [comment]
Done :)
