### ISSUE TITLE
Position Gizmo covering the entire object making the object not visible

### ISSUE THREAD

**Issue by MegsTan** [BabylonJS/Editor#200]
Hi @julien-moreau 

I noticed that when I create an object. The position gizmo covers the entire object making it not visible.

![Sphere](https://user-images.githubusercontent.com/44461836/88469583-bd023700-cf25-11ea-96da-af4229202db2.png)

**Comment by julien-moreau** [comment]
Hey @MegsTan !
You are right! I added some kind of transparency for plane gizmos. Do you think that would do the job?
![image](https://user-images.githubusercontent.com/2620127/88485504-7c7ed980-cf76-11ea-926d-5ffddddb750a.png)

**Comment by MegsTan** [comment]
Hi @julien-moreau ,

Yup, that will do. Thank you so much!!!!
