### ISSUE TITLE
babylon Blender exporter canceling the export when the characters has a rigify 

### ISSUE THREAD

**Issue by rvnosa** [BabylonJS/Editor#201]
I have a new set of character and it keeps canceling when exporting it to .babylon, even unckecked or check the "ignore the ik bones"
![blender_lwrQmioYJ8](https://user-images.githubusercontent.com/67937560/88490161-263c8580-cfcc-11ea-888b-15c5fcfc306d.png)

**Comment by julien-moreau** [comment]
Hi !
I'm not really familiar with Blender and Exporters and looks more like a question for the Babylon.JS Exporters project.

I suggest that you ask for help on the Babylon.JS forum here: https://forum.babylonjs.com

The forum has a great community that will help you more than me about blender and exporter :)

Thanks!

**Comment by rvnosa** [comment]
thank you for the big help

**Comment by rvnosa** [comment]
is there a babylon exporter group in discord?

**Comment by julien-moreau** [comment]
No problems, always a pleasure to help :)
I think not, at least I'm not in it

**Comment by rvnosa** [comment]
Thank you, I am already joined in the forum
