### ISSUE TITLE
v4.0.0-beta.4 - Animations not saved in scene? (.glb meshes)

### ISSUE THREAD

**Issue by vouse-cph** [BabylonJS/Editor#208]
When saving a scene/project, closing the editor, and opening it up again, the meshes with animations in the scene no longer exist. Printing to console "this.getScene().animationGroups.length.toString()" and "this.getScene().animations.length.toString()" both yielded "0" while running, when originally there were 4 animation groups with the associated meshes.

Current brute force workaround is to delete all the meshes with animations and manually place them in the scene again. The animations are lost when the editor closes again

**Comment by julien-moreau** [comment]
Hey @vouse-cph you are right, the animation groups were not parsed when reloading the project :(
It has been fixed and is now available on the branch "release/4.0.0". Anyway I'm releasing a new beta ASAP with that fix.

Thanks for reporting!

**Comment by julien-moreau** [comment]
@vouse-cph I recently released the beta.6 of the Editor that fixes this issue, can you confirm?

The beta.6 can be found here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta
And documentation still available here: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

Thanks :)

**Comment by vouse-cph** [comment]
@julien-moreau Thank you! I can confirm that the animations are indeed being saved in v4.0.0-beta.6. Great work!

**Comment by julien-moreau** [comment]
Perfect!! Don’t hesitate if you encounter another bug or want to provide some feedbacks, I’ll be a pleasure :)
