### ISSUE TITLE
v4 beta6 not showing script properties in inspector

### ISSUE THREAD

**Issue by blubberblah** [BabylonJS/Editor#209]
Hello!
I've noticed that script properties annotated with `@visibleInInspector` don't show up in inspector. I've even tried it with `player.ts` script within 3rd person shooter example project but had no luck. Maybe this is a bug?
Regards

**Comment by julien-moreau** [comment]
Ouch! I'm fixing ASAP.
Can you give me more informations about your environment?

OS?
Version of the editor? The beta6 is available now and fixed issues with webpack integration et.

Can you check the console in the editor and tell me if you see errors etc?

Thanks a lot :)

**Comment by blubberblah** [comment]
Hi Julien,
thanks for the quick reply! I'm on Win 10 (10.0.19041.450). Editor version is beta6 as downloaded from https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta.
I've not seen any errors in console. Is there any further Info I can give to you?
Regards

![shot2](https://user-images.githubusercontent.com/1374928/91602406-95125300-e96b-11ea-97ab-fedb2c9d8620.jpg)

**Comment by julien-moreau** [comment]
Hey, I can see in the co some that the command is not found. It is calling a command using NodeJS. Have you NodeJs installed? You can install from: https://nodejs.org/en/

This is required (still have to write that point in the documentation of the editor) as it is used to build the production code of your games/applications and transpile Typescript files.

Dont Forget to add "node" in your PATH environment variable.

Let me know if it works better :)

**Comment by blubberblah** [comment]
Hi Julien,
node is installed. I've manually opened a console at the specific location and got the same error as within the editor. Then I changed the forwardslashes to backslashes and it worked (see screenshot). Could this be a probem?

![image](https://user-images.githubusercontent.com/1374928/91652800-c89fcb00-ea9a-11ea-8a1e-c0e7599af608.png)

**Comment by blubberblah** [comment]
What I ended up doinig is changing the cosole to powershell. Now scripts get compiled, porperties show up in inspector and hooks gett called when running the project.

![image](https://user-images.githubusercontent.com/1374928/91656704-1b897a80-eabb-11ea-9277-42289c1f3a08.png)

**Comment by julien-moreau** [comment]
Wow !! Good catch!!

Using powershell was what I wanted to suggest. Anyway, thanks to your help, I fixed the usage of commands in win32. Just pushed on release/4.0.0.

I'm releasing ASAP. You can use powershell until I release the beta.7 of the Editor :)

Thanks again for that feedback :)

**Comment by blubberblah** [comment]
Thank you for the great editor Julien :-)

**Comment by julien-moreau** [comment]
Don’t hesitate if you have another bugs or feedbacks! =D
