### ISSUE TITLE
V3 + V4 issue with GLTF: Models broken when previewing

### ISSUE THREAD

**Issue by csotiriou** [BabylonJS/Editor#210]
Hello,

Thanks for your amazing work on the editor.

However, I am having some serious issues with both v3 and v4 - not sure if I am doing something wrong here.

What I am trying to do is:

1. Load the GLTF model in the editor (attached)
2. Add a single point light
3. "Play" the scene, verify that it's working correctly.
4. Export the scene as `.babylon` and import it from my website elsewhere. 

However, when I am displaying the model inside the editor, everything works correctly, but during the "Play and Debug" the model is completely destroyed.

Here are two screenshots from inside the editor (v3 and v4, different lights used). Everything seems to be in order.
![Screenshot 2020-08-30 at 12 36 54 PM](https://user-images.githubusercontent.com/1228484/91656011-d7e44000-eabd-11ea-8c8d-8830b2c88557.jpg)
![Screenshot 2020-08-30 at 12 37 18 PM](https://user-images.githubusercontent.com/1228484/91656018-ecc0d380-eabd-11ea-8743-76d9b0ac62af.jpg)

Here is how it looks when running it as a preview:

There are many errors thrown.

![Screenshot 2020-08-30 at 12 36 05 PM](https://user-images.githubusercontent.com/1228484/91656045-2691da00-eabe-11ea-80dc-d0a90b413412.jpg)
![Screenshot 2020-08-30 at 12 36 44 PM](https://user-images.githubusercontent.com/1228484/91656057-3d383100-eabe-11ea-9599-4c3bc34888bf.jpg)

### Model am I am using:
I used both the .glb and plain .gltf formats, I am getting the same results.
[Archive.zip](https://github.com/BabylonJS/Editor/files/5146558/Archive.zip)

Is this a bug, or I am doing something wrong?

**Comment by julien-moreau** [comment]
Hey thanks for reporting! Just fixed, the issue was that the gltf scene has multiple geometries that have the same Id. I fixed by overriding the id of each geometry when adding the meshes asset in the scene.

Also, your scene is just SO BIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIG (2000+ meshes etc.). I improved the loading/saving performances of the Editor thanks to you :)

Will be released ASAP. Do you have to possibility to build the version of the Editor yourself? If not, I'm doing my best to release the beta.7

Thanks

**Comment by csotiriou** [comment]
Wow, that was quick. Thank you so much!

I compiled from source, it seems that:

1. saving / loading this scene / model from the editor works.
2. Exporting to GLTF works now from the editor (previously, it wasn't working properly)
3. Viewing this GLTF works
4. Viewing the generated .babylon scene inside the sandbox works now (previously it wasn't working)
5. There is a notable performance difference when saving/loading
6. Loading the scene from my code is broken (I can load other scenes properly) - the model is corrupted / totally wrong (but in a different way than before).

I still can't quite figure out what is wrong with my code (if there is any problem)

Viewer.js:
```typescript
import ModelViewer from "../../components/ModelViewer";
import {DefaultRenderingPipeline, Engine, FreeCamera, Scene, SceneLoader, Vector3,} from "@babylonjs/core";

function onSceneReady(scene: Scene, engine: Engine) {
  const camera = new FreeCamera("camera1", new Vector3(0, 5, -10), scene);

  const pipeline = new DefaultRenderingPipeline("defaultPipeline", true, scene, [camera])
  pipeline.samples = 4;
  pipeline.fxaaEnabled = true;

  pipeline.bloomEnabled = true
  pipeline.bloomThreshold = 0.8;
  pipeline.bloomWeight = 0.4;
  pipeline.bloomKernel = 64;
  pipeline.bloomScale = 0.5;
  pipeline.imageProcessingEnabled = true;

  // This targets the camera to scene origin
  camera.setTarget(Vector3.Zero());

  const canvas = scene.getEngine().getRenderingCanvas();


  camera.attachControl(canvas, true);

  console.log("beginning importing pipeline...");

  SceneLoader.ImportMesh(
    null,
    "http://localhost:8080/",
    "exported_bathroom.glb",
    scene,
    (meshes) => {
      console.log("mesh loaded");
      // scene.createDefaultEnvironment();
      console.log("meshes: ", meshes.length);
      console.log("success");
    },
    null,
    (s, e, exception) => {
      console.error("null!", exception, e);
    }
  );
}

export default function Viewer() {
  return <ModelViewer onSceneReady={onSceneReady} />;
}

```

```typescript
import {Engine, EngineOptions, Scene, SceneOptions} from "@babylonjs/core";
import "@babylonjs/core";
import React, {useEffect, useRef, useState} from "react";
import "@babylonjs/loaders/glTF";
import "@babylonjs/loaders/OBJ";
import "@babylonjs/materials"

interface Props {
  onSceneReady: (scene: Scene, engine: Engine) => void;
  antialias: boolean;
  engineOptions: EngineOptions;
  adaptToDeviceRatio: boolean;
  sceneOptions: SceneOptions;
  onRender: (scene: Scene) => void;
}

export default (props: Partial<Props>) => {
  const reactCanvas = useRef(null);
  const { antialias, engineOptions, adaptToDeviceRatio, sceneOptions, onRender, onSceneReady, ...rest } = props;

  const [loaded, setLoaded] = useState(false);
  const [scene, setScene] = useState(null);

  useEffect(() => {
    if (window) {
      const resize = () => {
        if (scene) {
          scene.getEngine().resize();
        }
      };
      window.addEventListener("resize", resize);

      return () => {
        window.removeEventListener("resize", resize);
      };
    }
  }, [scene]);

  useEffect(() => {
    if (!loaded) {
      setLoaded(true);
      const engine = new Engine(reactCanvas.current, antialias, engineOptions, adaptToDeviceRatio);
      const scene = new Scene(engine, sceneOptions);
      setScene(scene);

      if (scene.isReady()) {
        props.onSceneReady(scene, engine);
      } else {
        scene.onReadyObservable.addOnce((scene) => props.onSceneReady(scene, engine));
      }

      engine.runRenderLoop(() => {
        if (typeof onRender === "function") {
          onRender(scene);
        }
        scene.render();
      });
    }

    return () => {
      if (scene !== null) {
        scene.dispose();
      }
    };
  }, [reactCanvas]);

  return <canvas ref={reactCanvas} {...rest} style={{width: 1000, height: 1000}} />;
};
```

The exported GLTF models from the editor get loaded properly. Other babylon files load correctly with this code. Only this .babylon file is corrupted as it seems (although I haven't conducted a thorough research yet).

If my code is wrong, then I believe this issue is resolved and can be closed. If it's correct, however, maybe this issue is not 100% fixed.

Again, I want to thank you for getting this fixed in such a short amount of time!

PS: Yes, the model is huge, it's a free model and I got it here: https://sketchfab.com/3d-models/bathroom-interior-68be8975cca1481c85c20b590e81c6a6 if you are interested in downloading it from the source.

**Comment by julien-moreau** [comment]
Hey @csotiriou 
Have you succeed? If not, can you send me the whole project so I can try to debug you? Thanks :)

**Comment by csotiriou** [comment]
@julien-moreau 

Yes, I have succeeded in what I was trying to do, by checking out from Github the entire project including your fix and compiling it!

Thank you very much!

**Comment by julien-moreau** [comment]
Excellent! You rox :)
