### ISSUE TITLE
v4.0.0-beta.6 volumetric light

### ISSUE THREAD

**Issue by aabbtree77** [BabylonJS/Editor#211]
After studying
https://forum.babylonjs.com/t/general-volumetric-fog/6202
https://www.youtube.com/watch?v=UKdWPj7VRu0&feature=emb_logo
I have two questions regarding volumetric lights:
1. Are they gone now in v4? They do not appear in scene's "Rendering" section that replaces "Post-Processes".
2. What was the algorithm for the implementation in v3, the one in babylon.js post-processes or the full ray marching?

It seems that babylon.js has a very simplistic post-processing for volumetric lights which has the problem that the light shafts/god rays disappear once the light source is not in the view frustum. On the other hand, the lighting in that youtube video indicates that some editor versions prior to v4 did have the ray marched implementation.

So there seems to be a potential conflict here, two different post-processing algorithms that may render volumetric lights. Could you please clarify this, whether v3 and prior versions did have ray marching. I find it difficult to understand how this works since I see no ray marching shader code inside the editor code base, and yet the lights in the video indicate the presence of ray marching.

Another problem is that I cannot see how v3 works in code because building v3.2.1-beta.1 or v3.2.1-beta.2 is still totally busted on Ubuntu 20.04 similarly to the issues #171, #172, #194, #195, while v3.2.1-beta.4 builds well, but its web version (via "npm run webserver) again does not work, it loads nearly everything and the editor window appears in the browser, but the scene has only some violet texture background with no objects in it and there is a spinner window "Importing extensions" going on indefinitely and everything just hangs on it. The terminal shows that 
```
"GET /lod-extension" Error (404): "Not found"
```

**Comment by julien-moreau** [comment]
Hey @AABBTree thanks for that feedback!

I haven't put these effects in order to be sure users will request it. I though no user used them so I'm adding it ASAP :)

I highly recommand to use the v4 so the v3 should not be an option ahah. As it is still a beta, I haven't replaced the download link as the documentation is also not updated on doc.babylonjs.com. Anyway I'm working on finalizing the v4 for a final release and a final documentation.

Do you confirm that the v4 that can be downloaded at https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta is working on your Ubuntu machine?

I keep the issue opened until I add the missing effect.
Thanks again!

**Comment by AABBTree** [comment]
Thank you for your response, I have added the second question in my edit, please see if you can clarify this. 

Regarding installs, the link above works (Linux downloads), but I would suggest not to use empty spaces in the executable names. The editor loads everything correctly with a few warnings about recommended webpack sizes and such. The icon on the Ubuntu desktop active bar is not displayed when the program runs (no avatar for babylon.js/editor), but this is a very minor detail.

The situation with git installs is more messy. It works after cloning only if one sets the branch explicitly
```
git checkout v4.0.0-beta.6
```

The default/master branch produces errors during the building as discussed in the previous issues around version 3.

**Comment by julien-moreau** [comment]
Hey @aabbtree77, it is planned to re-add these effects in Babylon.JS 5.0.0. I'll work on updating these effects and they'll be available in the Editor once they are available in the new Babylon.JS version :)
