### ISSUE TITLE
[question] V4.0.0-beta 7 editor. Create semitransparent materials

### ISSUE THREAD

**Issue by Juanmaramon** [BabylonJS/Editor#215]
Sorry for the noob question, but how can I create a semitransparent/transparent material without textures on the editor?

Thanks!

**Comment by julien-moreau** [comment]
Hey @Juanmaramon no problems :)
What do you mean exactly by transparent/semi-transparent? If you are talking about the overall transparency of an object at many degrees, you can play with the alpha value of the material assigned to the mesh. You can follow this documentation to apply a material: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/04%20-%20adding-materials/doc.md

I'm closing the issue by suggesting that you can ask your questions on the forum here: https://forum.babylonjs.com/ this will allow to other developers to see your problem but also the answer of the problem :)
