### ISSUE TITLE
Undoing scaling does not properly undo

### ISSUE THREAD

**Issue by alphabt** [BabylonJS/Editor#216]
When I undo a scaling it stretched the mesh further instead of returning to the previous scale.

1. For example, starting with the original scale for the sphere to the right:
![image](https://user-images.githubusercontent.com/6440237/93259274-71fde680-f754-11ea-90ed-c83f24fcd85e.png)

1. Scale it up on the y-axis using the scaling gizmo
![image](https://user-images.githubusercontent.com/6440237/93259301-80e49900-f754-11ea-9c32-dc2b6d9896d2.png)

1. **BUG**: Perform undo and it doesn't restore back to the original scale; it actually scales it up further. Notice the y-axis is now upside down too.
![image](https://user-images.githubusercontent.com/6440237/93259327-8c37c480-f754-11ea-9f0d-ce29474ed6a2.png)

1. Redo properly rescales it to the state after step 2
![image](https://user-images.githubusercontent.com/6440237/93259665-0a946680-f755-11ea-8914-6d725851249f.png)

Repro:
1. Go to http://editor.babylonjs.com/ (loaded with the default scene)
1. Use scale tool to scale any of the spheres
1. Undo via menu

Expected: Restores the scale
Actual: Scale further more, axis flip

A side issue is that the scale values in the property panel don't change on undo nor redo; they remained static.

**Comment by julien-moreau** [comment]
Hey @alphabt !
Thanks for reporting!

I can see that you are using the Editor v3. I highly recommand that you start using the Editor v4 right now as it is more stable/powerful. (projects of v3 are not compatible with v4)
I'm checking if I'm not having the issue on the v4 and will close once verified/fixed :)

You can download the beta here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta
And the doc still WIP: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

Thanks again for reporing and hope you'll get fun :)

**Comment by julien-moreau** [comment]
@alphabt any news ? :)

**Comment by alphabt** [comment]
Yes it works in the latest beta v4.0.0-beta.7 on macOS. Thanks for pointing that out!

**Comment by julien-moreau** [comment]
Excellent! Thanks again for reporting.
Don't hesitate if you encounter other bugs :)
Or use the forum to request new features / improvements :)
