### ISSUE TITLE
Adding a script to the universal camera on the default scene just works on the first run

### ISSUE THREAD

**Issue by RuiOrey** [BabylonJS/Editor#218]
Hi,
I created this script for the universal camera on the default scene:
```js
import { Scene, Color4, UniversalCamera } from 'babylonjs';

export default class Test implements IScript {
    // Public members
    public blackColor = new Color4(0, 0, 0, 1);
    private time = 0 ;
    /**
     * Constructor
     */
    constructor (public universalcamera: UniversalCamera, public scene: Scene) {

    }

    /**
     * Called once starting the script
     */
    public start (): void {
        // You can access the scene everywhere
        this.scene.clearColor = this.blackColor;

        // You can access the attached object everywhere
        console.log(this.universalcamera);
    }

    /**
     * Called on each frame
     */
    public update (deltaTimeMs: number): void {
        console.log(this.universalcamera);
        this.time = (this.time+ deltaTimeMs);
        this.universalcamera.position.x = Math.sin(this.time*0.01 )*6.2;
        // Your code...
    }

    /**
     * Called once the attached object has been disposed
     */
    public dispose (): void {
        // Called once the attached object has been disposed
    }
}

// Export the script as an attached script
// (attached to a node or scene)
exportScript(Test);
```
I attach it to the camera. 
It moves.
I hit stop and play again and it does stop.
If I click on other object and then in the camera again, the script is no longer attached.
This does not happen in other elements like the spheres.
I'm using the windows version 3.2.0 on windows 10 64, although that also happened on chrome.
Thanks and great work

**Comment by julien-moreau** [comment]
Hey @RuiOrey,
Sorry for being late, I was pretty unavailable these days. Now I'm back!! :)

Are you at an advanced state with your project using that Editor? If not, I suggest that you start using the version 4 of the Editor. It has been made to be easier to use/understand and is much more powerful/stable than the v3. I'm working hard on the version 4 to release it in few weeks. Would you be interested by this new version? If yes, only bugs will be fixed until the final release, there will not be any breaking change for projects :)

You can download the betas here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta
And the documentation still WIP: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

**Comment by RuiOrey** [comment]
Was just checking around the tools and the lib. I'm used to three.js and unity but checking the current status of babylon seems it evolved a lot during the last years.
Checking v4 now, having some troubles but probably I need to take a better look in all documentation.. 
I got some freezes on the building cache on my mobile pc (not on desktop) and from what I understand when I add a new script file I have to reload the project so it is recognized, probably due to the need of webpack to add it.
I also have some trouble understanding how to rotate the camera. Changing `absoluteRotation` does not seem to change nothing.
But looking very very good.
Thanks

**Comment by julien-moreau** [comment]
Just, what OS are you using exactly?
Just closing the issue for now, if you have any question really don't hesitate to use the forum (https://forum.babylonjs.com/) of Babylon.JS. You can use your github id to login :)

For the absolute rotation, I think you should change the `.rotation` property instead of `.absoluteRotation`

**Comment by RuiOrey** [comment]
Windows 10 64.
Thanks will follow up on forums if more doubts.

Julien Moreau-Mathis <notifications@github.com> escreveu no dia quarta,
7/10/2020 à(s) 12:54:
