### ISSUE TITLE
dat.gui rendering issue with "addColor"

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Editor#22]
@samjoch, found another issue with dat.gui in CSS when calling ".addColor"
The palette should be on the right (not bottom in the air)

Thanks!

<img width="286" alt="capture d ecran 2017-10-25 a 23 38 33" src="https://user-images.githubusercontent.com/2620127/32024659-a29845d6-b9dd-11e7-8390-2810ee3a855b.png">

**Comment by julien-moreau** [comment]
You should type "git checkout v2"

**Comment by samjoch** [comment]
So here is a situation. `w2ui` border-boxes all elements. https://github.com/vitmalina/w2ui/blob/master/src/less/src/layout.less#L10

That kills the layout component in [dat.gui](https://github.com/dataarts/dat.gui) and in particular the `color picker`. (cf. https://github.com/vitmalina/w2ui/blob/master/src/less/src/mixins.less#L13)

here is the [MDN](https://developer.mozilla.org/docs/Web/CSS/box-sizing).

**Comment by julien-moreau** [comment]
Thanks @samjoch !
Closing the issue
