### ISSUE TITLE
Morph Target is lost after closing editor

### ISSUE THREAD

**Issue by tianyihong** [BabylonJS/Editor#235]
Hi! I have imported a mesh with several morpht targets in editor v4.0.0-rc.1. I added it to the scene. MorphTargetsManager can work before I close the editor. And when I open the editor workspace again,  the mesh loses the morph target manager which have been added to the scene .
I'm not familiar with babylonjs editor. It that an issue ?

**Comment by julien-moreau** [comment]
Hey @tianyihong 
You are right! I reproduced and it is not the intended behavior: morph targets should be saved as well as geometries etc.
I'm fixing ASAP and will deploy once the bug has been fixed.

Sorry for that issue and thanks again for reporting!

**Comment by julien-moreau** [comment]
Hey @tianyihong just fixed the issue! I'm going to deploy ASAP!
Thanks again for reporting!
