### ISSUE TITLE
Suggestion: Watch project automatically default to be true

### ISSUE THREAD

**Issue by tianyihong** [BabylonJS/Editor#239]
Hi! This is just a small suggestion to Editor v4. 
I worked on Editor v4.0.0-rc.1. I attached my script to a mesh. I tried to modified my script in Visual Studio Code, clicked 'refresh' button on inspector script panel and then save the workspace. When I ran my application, the modified script was not updated. This really troubled a lot  when I try to debug my script. After enabling "Watch project automatically" option in preferences panel, it feels better to debug script. 
So I suggest to set "Watch project automatically" option to be true by default or provide developers a more detailed instruction about setting  preferences.

**Comment by julien-moreau** [comment]
Hey @tianyihong,
You are right, I'm going to improve the documentation and add a chapter focused on the preferences (including editor / workspace)
Will let you know once done, would love to get your feedback on the documentation as well :)

**Comment by julien-moreau** [comment]
Hey @tianyihong workspaces are now watched by default when creating a new workspace. I'm adding the documentation right now :)
