### ISSUE TITLE
This is less of an issue and more of a plea for help

### ISSUE THREAD

**Issue by TERRYTGPM** [BabylonJS/Editor#240]

**Comment by TERRYTGPM** [comment]
I need help
I can't understand how to edit the thing. I know its dumb nut please help me

**Comment by julien-moreau** [comment]
Hey @TERRYTGPM,
I'm not sure to understand what is your problem, have you tried reading this documentation first? https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

**Comment by TERRYTGPM** [comment]
I'll try to explain it the best I can. 
So, the thing is, you know how we write the code and shit, and for that we use stuff like visual studio code? yea. so I can't figure out how to do that.

**Comment by julien-moreau** [comment]
@TERRYTGPM sorry for the delay and I'm still not sure what is your problem, except installing Visual Studio Code on your computer, following this documentation (https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/07%20-%20attaching-scripts/doc.md) would be enough to write code :)

Please provide more details on what you are looking for

**Comment by julien-moreau** [comment]
@TERRYTGPM any news?

**Comment by TERRYTGPM** [comment]
maybe

**Comment by TERRYTGPM** [comment]
I'll get back to you in a few days
