### ISSUE TITLE
Add Support For Multiple Physics Engines

### ISSUE THREAD

**Issue by undefinederror** [BabylonJS/Editor#242]
Hi, just cloned the repo and opened the editor v4.
The editor looks neat! 

How would I enable physics? I see I can set the impostor on meshes but nothing happens when I play the scene.
I tried to look for documentation about it but found nothing

Thank you

**Comment by julien-moreau** [comment]
Hey @undefinederror
There is no documentation about physics at the moment as the Editor's documentation is still WIP
Anyway, physics is enabled by default in workspaces, when you add an impostor, are you sure that its mass is different from 0 ? Mass is equal to 0 by default if I'm not wrong

**Comment by undefinederror** [comment]
Hi @julien-moreau 
Thank you for your quick reply!

Yes you are right, I didn't set gravity in Scene. I did it now and it indeed works.
I see that cannonjs is the default engine. Should I wanna change it I suppose I should install the npm package and change that attaching a script to scene right?

**Comment by julien-moreau** [comment]
Hey,
You are right only cannon.JS is supported at the moment in the editor but switching to Oimo.JS and Ammo.JS is in my todolist. Unfortunately you can’t switch engine in that easy way at the moment, as the serialized scene stores the physics engine to be « CannonJS ». Which engine would you like to use ?

**Comment by undefinederror** [comment]
Hey @julien-moreau ,

I would like to use Ammojs
I tried onInitialize()
![image](https://user-images.githubusercontent.com/8209966/103080046-56b53980-45d5-11eb-86be-6cd30dfb699f.png)
I see I have to disable the physics engine before enabling a different one.
That inevitably also destroys all the Impostors created via editor :(
I have no idea what impact CannonJS being in the serialized scene would have

**Comment by julien-moreau** [comment]
@undefinederror you are right, physics impostors created by the Editor are not compatible with AmmoJS as the encapsulated impostor are created using CannonJS :(

I'm adding the option in the Editor to choose the physics engine to use. Once chosen, it'll re-create all impostors taking the same parameters as you provided using the default physics engine.

I'll let you know once done :)

**Comment by undefinederror** [comment]
Yes that would be great.
Thank you!

**Comment by julien-moreau** [comment]
@undefinederror done!
I'm adding a documentation on what developers should handle when changing the physics engine.

**Comment by undefinederror** [comment]
Hi @julien-moreau,
This is awesome. I am going to try it out and let you know

Thank you!

**Comment by julien-moreau** [comment]
I’m writing some documentation for the dev part. Because by default the project template imports cannonjs (in the index.html) and if the physics engine is changed, this import should be replaced by the desired engine (oimo or ammo in your case). If you don’t change this import, physics will not work anymore :)

**Comment by julien-moreau** [comment]
Hey @undefinederror just added the documentation: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/08%20-%20using-physics/doc.md
The last chapter "Choosing physics engine" will be the one for you

Don't hesitate to open another issue if you encounter any bug or have any feedback :)
