### ISSUE TITLE
How to disable animations in scene?

### ISSUE THREAD

**Issue by tianyihong** [BabylonJS/Editor#243]
Hi ! I have imported a glTF mesh with a default animation  and added it to the scene. The animation play automatically. When I started to play my game in browser, the mesh vertices is same as the vertices in the end frame of the animation. 
So how to disable animations in the editor in editor v4?

**Comment by julien-moreau** [comment]
Hey @tianyihong, this must be done by the Editor itself. In your case, morph target are animated so when the project is saved, the animated influences (and their modified values) are saved as well. I'm adding a fix to don't play animations automatically when instantiating meshes.

**Comment by julien-moreau** [comment]
Fixed!

**Comment by julien-moreau** [comment]
@tianyihong done! Will be deployed ASAP, or you can build your own editor using the branch "release/4.0.0" :)

**Comment by tianyihong** [comment]
> @tianyihong done! Will be deployed ASAP, or you can build your own editor using the branch "release/4.0.0" :)

Thanks a lot! Great work!

**Comment by tianyihong** [comment]
> Hey @tianyihong, this must be done by the Editor itself. In your case, morph target are animated so when the project is saved, the animated influences (and their modified values) are saved as well. I'm adding a fix to don't play animations automatically when instantiating meshes.

Sorry for disturbing you again. I built my own editor. It worked well. When I import a gltf skinned mesh, the coordinates work well. Howerver when I reopen the editor, the skinned mesh coordinates are messed up. And the mesh will rotate on x axis 90 degree.  After I click "Update Instantiated References..." button on mesh and update sub geomtry one by one, the mesh coordinate become correct.  Is that an issue ? Or is there any way to save the instantiated mesh's world matrix and apply it when editor reopen ?
