### ISSUE TITLE
v3 editor online particles-creator.js not found.

### ISSUE THREAD

**Issue by gai00** [BabylonJS/Editor#247]
Url: <http://editor.babylonjs.com/v3/>
I want to show this great editor to my friend, but it's not wokring.
```
system.js:4 GET http://editor.babylonjs.com/dist/particles-creator.js 404 (Not Found)
```
I got this error in console.

Chrome version: 87.0.4280.109 (64-bit)
OS: Chrome OS

**Comment by julien-moreau** [comment]
Hey @gai00 thanks for reporting! Just reproduced the issue, I'm deploying the fix asap!

**Comment by julien-moreau** [comment]
Hey @gai00 fixed!
You can now access http://editor.babylonjs.com/v3/ without error :)

Thanks again for reporting!
