### ISSUE TITLE
how can I configure engine in  v4.0.0-rc.1

### ISSUE THREAD

**Issue by TanLocc** [BabylonJS/Editor#253]
I am using version v4.0.0-rc.1, I don't  how to configure engine, as its instructions are in physics, but I don't find.

**Comment by codehasbug** [comment]
You can build from source code which branch is 'release-4.0.0'.

**Comment by TanLocc** [comment]
Can you specify more?Please.

**Comment by codehasbug** [comment]
```shell
git clone https://github.com/BabylonJS/Editor.git
cd Editor
git checkout release/4.0.0
npm install
npm run build
```
After that you can found a folder "electron-packages"
cd electron-packages
you can see files of binary.
system: Ubuntu 20.04
you can follow "README.md" file to build them on other platform, If you use different system.

**Comment by codehasbug** [comment]
![2021-01-22 11-14-58](https://user-images.githubusercontent.com/41138618/105441253-1e238100-5ca3-11eb-96c8-3458a5b2bb88.png)
I guess you want to see these options. If that is it, you can build this project by youself. I already wrote an example on Linux platform.

**Comment by TanLocc** [comment]
Unfortunately when I use the Windows system, I will probably wait for you to release a new version.
Thank guy very much !

**Comment by julien-moreau** [comment]
Hey thanks @codehasbug for you help!
As there is a need, the rc.2 will be released today to fit your needs :)

To change the physics engine and make the project working I have created the documentation available here: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/08%20-%20using-physics/doc.md

**Comment by julien-moreau** [comment]
@TanLocc deployed!
