### ISSUE TITLE
Add Pure Cube Texture

### ISSUE THREAD

**Issue by TanLocc** [BabylonJS/Editor#254]
I am using version v4.0.0-rc.1, how to use function of add Pure Cube texture, this function seems incomplete .

**Comment by julien-moreau** [comment]
Hey @TanLocc 

To add a pure cube texture, you can click on the "Pur Cube Texture..." menu in the textures assets tab. Then, you'll have to provide all the 6 textures according and click "ok". Is that the feature you are looking for?

![image](https://user-images.githubusercontent.com/2620127/105988502-003d8e00-60a0-11eb-8557-f888bf52ab95.png)

**Comment by julien-moreau** [comment]
@TanLocc any news? :)

**Comment by julien-moreau** [comment]
Still can't reproduce, closing the issue until the problem re-appears :)
