### ISSUE TITLE
Can I use Editor on browser and server in docker?

### ISSUE THREAD

**Issue by gai00** [BabylonJS/Editor#257]
I want to deploy a dev-server on my Nas.
now I can see the editor on browser.

My steps:
1. docker run -it -p 1338:1338 node bash
2. apt update  && apt install -y git
3. git clone --depth=1 https://github.com/BabylonJS/Editor.git
4. cd Editor
5. node ./script/install.js
6. npm run compile
7. npm run webserver
8. [open browser]: http://localhost:1338/index-local.html

Can I load / save project on server?
even multi-editor online together?

**Comment by julien-moreau** [comment]
Hey,
Unfortunately the Editor has not been designed to support that kind of use directly.
In fact, I'm working on the latest version of the Editor that is being to be released (rc.2 will be released ASAP) and has been made from scratch. It is now based on a pure electron app and is available on the branch release/4.0.0.

The downloads are available here: https://github.com/BabylonJS/Editor/wiki/BabylonJS-Editor-v4.0.0-beta
And documentation is available here: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

For my information, what is the exact need of your request? Do you need collaborative work?

**Comment by julien-moreau** [comment]
@gai00 any news?

**Comment by gai00** [comment]
> @gai00 any news?

Sorry for late reply. (busy before lunar year in asia)

I'm learning/playing babylon.js for interest.
For now, I don't need collaborative working... 
but it could be a good feature.

I need docker server version becus I'm using chromebook, and it run editor in crostini (base on lxc), with bad webgl performance...
so I ask it for chrome browser (native).

thanks for your reply and tag me, happy coding.

**Comment by julien-moreau** [comment]
Thanks for the info @gai00 
Closing the issue for now as Chromebooks and web versions of the Editor are deprecated :)

have fun!
