### ISSUE TITLE
New empty project won't run unless I disable physics

### ISSUE THREAD

**Issue by Xiode** [BabylonJS/Editor#259]
Hello! I'm trying to start exploring BabylonJS, but when I downloaded editor 4.0.0-rc2 and tried to run an empty project, I got the following errors in browser:

**`GET http://localhost:1338/node_modules/cannon/build/cannon.js net::ERR_ABORTED 404 (Not Found)`**

**`Unable to load from ./scenes/scene/scene.babylon: importScene of scene.babylon from Babylon.JS Editor version: v4.0.0-rc.2, exporter version: v4.2.0`**

Some surface-level reading tells me that Cannon is the default physics engine, so I changed it, but got the same result from Oimo and Ammo. Un-checking the `Physics Enabled` box allows the project to run, but I'm not sure what to do to fix it! I've tried re-installing and running the editor as administrator to no effect.

edit: Might be handy to share some specs. 
- Windows 10 Home (version 20H2)
- Chrome (version 88)
- Ryzen 5 3600X
- Nvidia GTX980

**Comment by julien-moreau** [comment]
Hey @Xiode,

sorry for thé delay. I looks like cannon doesn’t exist you are right. Have you installed the dependencies? Using « npm install »?

the editor should do it for you at the first launch but may fail if the command « node » is not available in your environment. Do you have nodejs installed?

**Comment by julien-moreau** [comment]
Hey @Xiode any news? :)
