### ISSUE TITLE
How to use scene.debugLayer.show() ?

### ISSUE THREAD

**Issue by HouLingLXH** [BabylonJS/Editor#260]
when use the api ，i get the error： 

  babylon.inspector.bundle.js:1 Uncaught TypeError: Cannot read property 'GUI' of undefined
      at VM24 babylon.inspector.bundle.js:1
      at VM24 babylon.inspector.bundle.js:1

  debugLayer.js:97 Uncaught TypeError: Cannot read property 'Inspector' of undefined
      at DebugLayer../node_modules/@babylonjs/core/Debug/debugLayer.js.DebugLayer._createInspector (debugLayer.js:97)
      at debugLayer.js:164
      at HTMLScriptElement.script.onload (tools.js:367)

**Comment by julien-moreau** [comment]
Hey @HouLingLXH,
It looks like BabylonJS is not defined on the window (including GUI, don’t forget ton import « @babylonjs/gui » in that case)

I’m checking if there is a special way to show debug layer when using ES6 modules

**Comment by julien-moreau** [comment]
Hye @HouLingLXH 
I just found a similar problem here: https://forum.babylonjs.com/t/trying-add-debug-layer-not-working/18184/7 but it has a solution :) Can you tell me if if it works for you?

Thanks!

**Comment by HouLingLXH** [comment]
Thanks for your help. I get the solution from https://forum.babylonjs.com/t/unable-to-open-the-inspector/1208.  Now I can open the inspector,but it still have promblem : https://forum.babylonjs.com/t/editorv4-0-use-api-scene-debuglayer-show-get-error/18613

**Comment by julien-moreau** [comment]
Hey @HouLingLXH have you solved your problem? It looks like the forum post became inactive

**Comment by julien-moreau** [comment]
@HouLingLXH any news? :)
