### ISSUE TITLE
How to get script from another mesh?

### ISSUE THREAD

**Issue by HouLingLXH** [BabylonJS/Editor#261]
For example, I add the test1.ts to box,and add the test2.ts to sphere,
how to get the objects in test1.ts to use in test2.ts?

**Comment by PartyGodTroy** [comment]
You've got a couple of options the way I see it.

You can have test1.ts and test2.ts give the object they are attached to a specific name, id, or tag and then look them up in the scene.

`export class Test1 extends TransformNode {
    test2:Test2
    public onStart(): void {
        const scene = this.getScene()
        this.test2 = scene.getNodeByName('hello') as Test2
        // Access properties on test2
        this.test2.light.intensity = 2;
        // or look up anyobject test 2 created
        scene.getLightByName('light_1')
    }
}
export class Test2 extends Mesh{
    light:Light
    // Set name/id in onInitialize or in the constructor so it is already assigned when onStart is called
    public onInitialize(): void {
        this.name = 'hello'
        this.light = new HemisphericLight('light_1', Vector3.Down(), this._scene)
    }
}
`

**Comment by julien-moreau** [comment]
@PartyGodTroy you are right!

The editor also provides decorators that can be used in class to retrieve object references. The available decorators are:
- @fromScene searchs for the object which has the specified name in the overall scene
- @fromChildren searchs for the object which has the specified name in the current object's children.

For example, having 2 named objects in the scene ("cube" and "ground")
The ground script may look like:
```typescript
import { GroundMesh, Mesh } from "@babylonjs/core";

import { fromScene } from "../decorators";

export default class MyCubeComponent extends Mesh {
    @fromScene("ground")
    private _ground: GroundMesh;

    ....

    /**
     * Called on the scene starts.
     */
    public onStart(): void {
        console.log(this._ground);
    }

    ....
}
```

And the cube script may look lile:
```typescript
import { GroundMesh, Mesh } from "@babylonjs/core";

import { fromScene } from "../decorators";

export default class MyGroundComponent extends GroundMesh {
    @fromScene("cube")
    private _cube: Mesh;

    ....

    /**
     * Called on the scene starts.
     */
    public onStart(): void {
        console.log(this._cube);
    }

    ....
}
```
