### ISSUE TITLE
How to get the external data when I'm in editor 's script?

### ISSUE THREAD

**Issue by HouLingLXH** [BabylonJS/Editor#262]
For example,  in the index.html:
<body>
    <canvas id="renderCanvas"></canvas>

    <script type="text/javascript">

        var testValue = "test";
        window.game = new window.game.Game();
    </script>
</body>

How to get the "tsetValue" in the script when I create in Editor?

**Comment by julien-moreau** [comment]
Hi @HouLingLXH,

Unfortunately there is no built-in tools to perform that action.
Anyway, the scripts you create are capable of requiring any other ts file in the project. You can for example store all global properties in a global object that will be required by the editor's scripts.

Else, if each object should have its own value, you can use the decorators as explained here: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/07%20-%20attaching-scripts/doc.md (see section named **"Customizing scripts in editor"**)

**Comment by julien-moreau** [comment]
@HouLingLXH does it work for you?
