### ISSUE TITLE
the build script does not work

### ISSUE THREAD

**Issue by tvortsa** [BabylonJS/Editor#265]
the build script does not work, the script specifies version 3.2 and not 4.0 in the storage.ts on line 134 - an error

ts - sucks!

**Comment by julien-moreau** [comment]
Hi @tvortsa 

I suggest that you start using the branch "release/4.0.0" instead of the master branch (which contains the version 3). The branch release/4.0.0 contains the incoming release of the Editor version 4.

Is there a real need to use the version 3?

You can find more informations here: http://editor.babylonjs.com/
And the documentation here: https://github.com/BabylonJS/Editor/blob/release/4.0.0/doc/00%20-%20welcome/doc.md

**Comment by julien-moreau** [comment]
@tvortsa any news?

**Comment by tvortsa** [comment]
i dont call it "news"  : (
![image](https://user-images.githubusercontent.com/78345/112135140-824cbd80-8bde-11eb-91c5-67953504c31d.png)

**Comment by tvortsa** [comment]
@julien-moreau any news?

**Comment by julien-moreau** [comment]
Hey thanks for the reminder !
You’ll have ton install the essential tools for windows unfortunately. There is the link and the tutorial on the Readme: https://github.com/BabylonJS/Editor/blob/release/4.0.0/README.md

**Comment by tvortsa** [comment]
My pleasure, but i cant work it out, im sorry bit avery time when i need to take windows-build-tools etc. its just dont work for me (
Im sorry but as i sad : "its dont work!"

TRACKER : error TRK0005: не удалось обнаружить "CL.exe". Не удается найти указанный файл. [D:\DEV\JS\babylon\editor4.0\Editor\node_modules\node-pty\build\conpty.vcxproj]

**Comment by julien-moreau** [comment]
Unfortunately, I can't support the installation problems of the windows-build-tools, are you sure that you have launched powershell as administrator etc.? Are you in a company context?

**Comment by julien-moreau** [comment]
@tvortsa if you still can't install the window-build-tools using Powershell (which are containing only the essential tools for building), you can simply install Visual Studio Community Edition. This will install all required tools including the one that we need here: https://visualstudio.microsoft.com/fr/

**Comment by julien-moreau** [comment]
@tvortsa have you solved the problem?
