### ISSUE TITLE
How do I add Actions in 4.0.0-r2?

### ISSUE THREAD

**Issue by lanrosta** [BabylonJS/Editor#267]
I am new to relatively Babylonjs, but an experiences web developer and 3D artist. I am trying to add interactivity to my Mesh objects in the Editor, but I cannot find an easy or right way to do this (there are no examples of this for some reason). I did find this article, but it is for a really old version of the Editor: (https://medium.com/babylon-js/programming-with-the-babylon-js-editor-ddab887c243a).

 Can someone please provide a simple example of how I can attach a script to a Mesh object that allows me to use Actions?

**Comment by julien-moreau** [comment]
@lanrosta as answered on the other issue, you can use the graph editor to create actions. This tool is much more advanced than the actions builder, even if it's in beta :)
