### ISSUE TITLE
Where is the Graph Editor in 4.0.0-r2?

### ISSUE THREAD

**Issue by lanrosta** [BabylonJS/Editor#268]
I'm not seeing any way to access the Graph Editor in this version. Is is coming, or was it dropped?

**Comment by julien-moreau** [comment]
Hi @lanrosta the graph editor is still available in the assets under the name "Visual Scripts" (rename was asked by the community).
You can add a new graph by giving it a name and double-click it to open the graph editor.

This is still a beta version of the component and is subject to changes/improvements. Unfortunately no documentation exists at the moment. I suggest that you use the forum to ask questions about the Graph Editor here: https://forum.babylonjs.com/

<img width="665" alt="Capture d’écran 2021-03-22 à 17 33 35" src="https://user-images.githubusercontent.com/2620127/112024690-bcfa1b80-8b34-11eb-8752-9a69a44d9a51.png">
