### ISSUE TITLE
where is app ?

### ISSUE THREAD

**Issue by tvortsa** [BabylonJS/Editor#274]
So, as i said : build script is dont work for me on windows, i choose Windows WLS Ubuntu and its work for build but where is the app!? How i can run my build !?

Seriusly guys are you sure that you know what you doing ?

**Comment by julien-moreau** [comment]
Hi @tvortsa,

I think we know what we do. Using WLS Ubuntu then the Editor will be built for Ubuntu.
In the folder "electron-packages/" you'll find all outputs of the Electron build.

The Editor is using native modules that must be compiled for the platform. Please try to solve the other issue first (installing windows-build-tools) and everything will work :)

I'm closing this one as it is a duplicate

**Comment by tvortsa** [comment]
I dont ask "where is all outputs of electron build" i ask HOW I CAN LAUNCH the babylon editor? 
I know , if i make buld by ubuntu i fet build for ubuntu but how i can start the app for ubuntu !?
somrthing like this console comands?:
> /electron-packages/run-my-f**g-app-cause-julien-moreau-said-you-must-! 
!?
Are you hear me or yourself?

**Comment by julien-moreau** [comment]
If you build for Ubuntu then you'll need a Ubuntu OS installed on your computer :)
WSL Ubuntu is not enough as it doesn't allow to create windows etc.
