### ISSUE TITLE
Unable to load "scene.babylon" which created by Babylon.JS Editor, How to resolve it?

### ISSUE THREAD

**Issue by codehasbug** [BabylonJS/Editor#275]
Hi, I found when my Vue.js project import the "scene.babylon" by the `SceneLoader.Append(rootUrl, filename, scene, onSuccess())` method, it shows  
`Unable to load from http://127.0.0.1:8082/scene.babylon: importScene of scene.babylon from Babylon.JS Editor version: v4.0.0-rc.2, exporter version: v4.2.0`  
![Error](https://user-images.githubusercontent.com/41138618/114664048-c0488780-9d2d-11eb-9f83-54a5fc33fe0c.png)

I try to check all of my config, and import an official babylon file to compare the difference. but I still don't know how to resolve it.   
this is a part of my codes  
```js
export default {
  name: "BabylonLoadPage",
  data(){
    return {
      canvas: '',
      engine: '',
      scene: ''
    }
  },
  mounted() {
    this.canvas = document.getElementById("renderCanvas");
    this.engine = new Engine(this.canvas, true);
    this.scene = new Scene(this.engine);

    window.addEventListener("resize", () => {
      this.engine.resize();
    });

    SceneLoader.Append("http://127.0.0.1:8082/", "scene.babylon", this.scene, () => {
      this.scene.executeWhenReady(()=>{
        console.log(this.scene)
        // Attach camera.
        if (!this.scene.activeCamera) {
          throw new Error("No camera defined in the scene. Please add at least one camera in the project or create one yourself in the code.");
        }
        this.scene.activeCamera.attachControl(this.engine.getRenderingCanvas(), false);

        // Render.
        this.engine.runRenderLoop(() => this.scene.render());
      })

    })
  }
}
```
  
and If I use the `ImportMeshAsync` method, it work, but I have to create and adjust new camera and new light.  This is that code.  
```js
SceneLoader.ImportMeshAsync("", "http://127.0.0.1:8082/", "scene.babylon");
const camera = new ArcRotateCamera("camera", -Math.PI / 2, Math.PI / 2.5, 15, new Vector3(0, 0, 0));
camera.attachControl(this.canvas, true);
new HemisphericLight("light", new Vector3(1, 1, 0));
```
![model](https://user-images.githubusercontent.com/41138618/114664332-233a1e80-9d2e-11eb-9e30-cb3e76e6f7d2.png)

### thanks!

**Comment by codehasbug** [comment]
I made a stupid mistake, I found my `index.html` file didn't adding my physic engine. Now I have solved the error. I will close the issue. Any way, thanks.

**Comment by julien-moreau** [comment]
Hi @codehasbug !
So sorry for the delay, I'm really happy that you found the solution!

The first solution is to add the physics engine you use in your project, like you did by adding the link in your index.htm file.
The other solution is, if you don't use physics in your project, to disable physics in the scene you'd like to export.

Physics can be disabled in a scene by selecting the scene in the graph and by unckecking "Enabled" in the inspector, like:

<img width="329" alt="Capture d’écran 2021-04-16 à 18 40 15" src="https://user-images.githubusercontent.com/2620127/115056465-30e4d500-9ee3-11eb-8ee1-f86875f66651.png">
