### ISSUE TITLE
http://myeditor.cool invitation

### ISSUE THREAD

**Issue by sskyy** [BabylonJS/Editor#276]
Hello, I'm the author of MyeditorCool. [http://myeditor.cool](http://myeditor.cool) is website reads user's file in github/onedrive/etc. through openapi, and allow user to edit it with any editor published to npm and has 'myeditorcool' field in package.json.

By supporting myeditorcool, your editor can soon be used by users to edit their own file online without installing anything!

I want to invite your editor to join myeditorcool, be our recommended editor. Only a few works need to be done, the docs are here: https://github.com/MyEditorCool/editors/blob/master/DevelopAnEditor.md. Looking forward to your reply.

**Comment by julien-moreau** [comment]
Hey @sskyy thanks a lot for this invitation!

Unfortunately the Babylon.JS Editor is not intended to run in a web browser as it is fully based on Electron :(
Keep up the good work!
