### ISSUE TITLE
The editor Scenes and the post-play Scenes are completely different

### ISSUE THREAD

**Issue by KitStarLee** [BabylonJS/Editor#286]
#### Very urgent, it seems to be a clear coat problem
![image](https://user-images.githubusercontent.com/24741508/120743036-c50a0a80-c52a-11eb-878f-075b2730bdb6.png)
![image](https://user-images.githubusercontent.com/24741508/120743476-ad7f5180-c52b-11eb-8055-d8cbb3ca952c.png)

**Comment by KitStarLee** [comment]
Very urgent, work cannot continue @julien-moreau 。Hope to get your help, thank you very much

**Comment by julien-moreau** [comment]
Hi @KitStarLee 
I reproduced! It looks like PBR material is not the same once serialized (when project is being saved). I'm checking the problem and come with a solution ASAP

**Comment by KitStarLee** [comment]
@julien-moreau Thank you for your attention

**Comment by julien-moreau** [comment]
Hi @KitStarLee 

Can you try playing with the `Metallic F0 Factor` property of your materials in the inspector? It looks like this parameter is applied differently before and after serialization.

**Comment by marcobertagna** [comment]
I have the same problem. I've try to set Metallic F0 Factor, it improves, but anyway there are differences. Could it be a gamma problem?

**Comment by julien-moreau** [comment]
Hi !

I finally reproduced the bug in the Babylon.JS Playground. The bug has been reported here: https://forum.babylonjs.com/t/problem-when-parsing-pbr-and-environment-textures/21845
Once fixed, the editor will be released with that fix (probably 4.0.2)

**Comment by marcobertagna** [comment]
Great! Thanks!

**Comment by julien-moreau** [comment]
Deployed! You can update the editor to the version 4.0.2 (here: http://editor.babylonjs.com/) or use the notification available in the editor to download the latest version.

To fix the problem, simply open the project and re-save. Please let me know if that works for you :)

**Comment by marcobertagna** [comment]
Fantastic news! I try it soon!

**Comment by marcobertagna** [comment]
@julien-moreau I try the version 4.0.2. the fix works! 
I notify you that the fix works on new projects, while on those created previously, it keeps having the same error. This is not a problem for me, but I'm saying it for your information.
