### ISSUE TITLE
When to launch a formal V4 version？

### ISSUE THREAD

**Issue by tidus2020** [BabylonJS/Editor#287]
I'm looking forward to use it early.

**Comment by julien-moreau** [comment]
Hi @tidus2020 

I would say ASAP :)
I'm adding some missing features for collisions and I'm done! What's missing is still more documentation but I'm working on.

When do you plan to use it?

**Comment by julien-moreau** [comment]
@tidus2020 done :) https://forum.babylonjs.com/t/introducing-babylon-js-editor-v4-0/21608
