### ISSUE TITLE
How to import mesh in runtime ? v4.0.1

### ISSUE THREAD

**Issue by HouLingLXH** [BabylonJS/Editor#295]
Before v4.0.1, I can use the API (SceneLoader.ImportMesh) to import mesh from local or server. 
Before ,I put the gltf in scenes folder,and then ,I can import it like:

 SceneLoader.ImportMesh("", "/scenes/", "test.gltf", this._scene, (meshes) => {

         })

But now, I get the error:
  Unable to import meshes from /scenes/test.gltf: importMesh of unknown

Can you help me？ thanks

**Comment by julien-moreau** [comment]
Hi @HouLingLXH :)

It looks like the loaders are not registered. In the index.ts file (at root of the src folder) can you put in the imports:
```typescript
import "@babylonjs/loaders"
```

By default, the editor and its projects are optimized to work with the .babylon format (allows incremental loading, LODs, etc., complex materials etc.). This is why you'll have to import loaders as your case is out of the default behavior.

Please let me know if it works for you. Else, please post questions and bug reports on the forum (https://forum.babylonjs.com/) so user will have benefit of your questions and solutions :)

Thanks a lot !

**Comment by HouLingLXH** [comment]
It worked when I impot it in my ts file , but the index.ts, because index.ts will be coverage. Thanks.
