### ISSUE TITLE
Environment texture not possible to be applied globally

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#31]
Hi **Julian**:

I'm here again with a battery of "wishes" to be included in your awesome **BJS Editor**. For your convenience I'm sending each one as a different issue.

The first of them is to have a mechanism which enable us to **set the environment texture in a global way**, not as a per material basis, as we think is the common case.

Best regards.

**Comment by julien-moreau** [comment]
That’s excellent, I’ll fix ASAP each feedback you give me :)

Will check if Babylon.js already allows me to do that, else, I will add this feature into the editor as a scene option (like « Default Environment Texture)

**Comment by vortice3D** [comment]
Hi **Julien**:

Yes this is the type of solution with were thinking about.

Thank you very much.

**Comment by julien-moreau** [comment]
Just fixed and deployed :) https://github.com/BabylonJS/Editor/commit/0fb925b2e52e6bc42179308c9f3f3845ce7cfaed
