### ISSUE TITLE
complex animation in glb format can not render in web project or play scene or sandbox, function in editor preview

### ISSUE THREAD

**Issue by Blame4** [BabylonJS/Editor#319]
simple animation like box transform function in all scene.
but complex animation like _bee_idle of Win10 built-in model(attached below), can not play after exported as .babylon, but can play as original glb  format.
How can I put the glb model in one .babylon file with functioning animation group(the animation groups exist, but not functioned).
It works when  the imported as glb format
[Bee.zip](https://github.com/BabylonJS/Editor/files/7299055/Bee.zip)
.

**Comment by julien-moreau** [comment]
Hi @Blame4 !
Thanks for that feedback!

I'm pretty sure (but I have to verify) that the problem is due to the absence of pose matrix once the model is exported as .babylon file. To be sure, would it be possible to share the original glb model?

**Comment by Blame4** [comment]
Sorry, I missed.It comes from built-in 3D viewer in Win10.
[Bee.glb.zip](https://github.com/BabylonJS/Editor/files/7325924/Bee.glb.zip)

**Comment by julien-moreau** [comment]
Hi @Blame4 I'm on it :)

**Comment by julien-moreau** [comment]
Looks like it has been fixed
