### ISSUE TITLE
Attribute "Use Roughness From Metallic Texture Green" doesn't work

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#32]
Hi **Julian**:

We have found that in v1.2, attribute "Use Roughness From Metallic Texture Green" doesn't work. It worked on earlier versions of the editor though.

Best regards

**Comment by vortice3D** [comment]
You're welcome!

Best regards.

**Comment by julien-moreau** [comment]
Fixed https://github.com/BabylonJS/Editor/commit/5d86327f9e9ad97c54331afda5a69803118d0cf6
And tested using this model with blue/green metallic values: http://www.babylonjs.com/demos/pbrglossy/
