### ISSUE TITLE
Inspector Error Rendering Component

### ISSUE THREAD

**Issue by andreaghiri** [BabylonJS/Editor#329]
Hi, maybe it's noob question since I'm new to Babylon.JS Editor, but everytime I click on the "Rendering" tab in the inspector panel, every tab disappears and a message pops up in the middle of the panel: "Error rendering component":
![Inspector_Error](https://user-images.githubusercontent.com/95026382/143428184-efe4b1b1-3698-4835-8f92-bb48000f280d.png)
In the scene there are a light gltf file, some textures and a .env environment.
How can I solve it?
Thank you in advance!

**Comment by julien-moreau** [comment]
Hi @andreaghiri !
So sorry for my late !

I just tried to reproduce but without success. In the top “Main toolbar → Edit → Preferences” there is checkbox that you can check to see the Editor’s console (it is called “Enable Electron DevTools”). Then, click the green button “Ok”.

Once done, can you restart the Editor, navigate until you reproduce the error and then paste all the console logs here? That would help me a lot as I fail when I try to reproduce :)

Thanks a lot !

**Comment by andreaghiri** [comment]
Thank you @julien-moreau, we can continue this topic on the thread in the Babylon forum:
https://forum.babylonjs.com/t/editor-error-rendering-component-inspector-gone/25174/7
Thanks a lot for your support,
Andrea
