### ISSUE TITLE
Scripts launched by VLC??

### ISSUE THREAD

**Issue by ernest4** [BabylonJS/Editor#330]
Nice work on the project!

OS: mac

This is weird but for some reason opening scripts from the editor for editing keeps using **VLC media player** instead of VSCode.

When I check the project files it assumes the **.ts** files are VLC by default, quite bizarre.

<img width="668" alt="Screenshot 2021-12-01 at 08 41 14" src="https://user-images.githubusercontent.com/35740142/144201188-dab57367-cb12-4e96-99bf-b9a23286b7a7.png">

I can't seem to find a way to set it so _all_ of those files can be opened with VSCode either. I can set it one file at a time only haha.

This looks like issue with Mac file system treating these files like this, not specific to Babylon editor (heres another random folder with typescript files). 
<img width="197" alt="Screenshot 2021-12-01 at 08 53 09" src="https://user-images.githubusercontent.com/35740142/144202737-852666b5-b632-41ce-b03f-82dc7168195a.png">

So technically I suppose it's end users (Mac) problem, but it is quite disorienting having to deal this for the first time ever. Normally you're in VSCode by default so all the files get interpreted properly.

That said is there no way to force the Editor to default try open the .ts files with VSCode and only when VSCode is not present on the system, default to something else? (sorry, I've no experience with electron haha, or desktop app dev for that matter haha)

**Comment by RaananW** [comment]
That's an OS file extension association. This will happen with any .ts file you have, not only the editor's generated files.

You should follow this - https://www.macrumors.com/how-to/how-to-manage-file-associations-in-macos/ , and make sure .ts files are loaded using vscode.

If you want to open an entire directory, use vscode's "open" option and select the folder. 

Regarding this:



> That said is there no way to force the Editor to default try open the .ts files with VSCode and only when VSCode is not present on the system, default to something else? (sorry, I've no experience with electron haha, or desktop app dev for that matter haha)

I'll let @julien-moreau answer :-)

**Comment by julien-moreau** [comment]
Hi @ernest4 ! I was searching for an answer and realized @RaananW already answered!
The link RaananW shared works perfectly (like this one, even old: https://apple.stackexchange.com/questions/780/problem-with-always-open-with-in-os-x). Associating files depends on the OS and should be configured on the OS itself.

I agree that the Editor can force using VSCode. Unfortunately, even if the editor is optimized to work with VSCode (shortcuts to open the project in VSCode, remote debug support, etc.), it should let the user choose which code editor to use to open TS files. For example, there are still a lot of developers preferring Atom than VSCode

Let me know if following the tutorial RaananW shared works and I'll close the issue :)

**Comment by ernest4** [comment]
Hey thanks guys! Changed it at OS level, all good now :)

Yeah defaulting to VSCode open was bit of a stretch there :P 
Thanks!

**Comment by julien-moreau** [comment]
Perfect ! I'm closing the issue and I'll add some documentation about it :)
