### ISSUE TITLE
Menu problem when a large number of  sub meshes were merged

### ISSUE THREAD

**Issue by jter** [BabylonJS/Editor#337]
1. Add a gltf contains 1700+ meshes.
2. Merge some of them.
3. Right click on the merged mesh.
4. Items such as 'Locked' disappeared and the menu can't scroll up or down.

Babylonjs Editor 4.0.5 on Mac 11.06

<img width="316" alt="image" src="https://user-images.githubusercontent.com/3131813/147383816-7b82bf5d-67e8-466e-9361-bc2cc858c097.png">

**Comment by julien-moreau** [comment]
Hi @jter ! Nice catch !
I'm fixing it by adding a maximum height with scroll support in case there are too much submeshes.

Thanks for reporting!

**Comment by julien-moreau** [comment]
@jter fixed!
Will be deployed in few hours :)

**Comment by julien-moreau** [comment]
Done! @jter
