### ISSUE TITLE
Please add UNDO

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#34]
Dear **Julien**:

Well the title of this issue is auto-descriptive.

We think the UNDO functionality is a must in each production tool.

Best regards.

**Comment by julien-moreau** [comment]
I totally agree!
Unfortunately, the current technical stack doesn't allow me to add undo/redo (expected the V1 to be more a "scene viewer"). Anyway, let's add the flag "V2" as I'm working on the version 2.0 that will implement undo/redo! The version 2 has to fit all features for creation/debug/deploy

**Comment by julien-moreau** [comment]
So I keep this issue opened and will try to give you a deployment date for the V2 which would be soon

**Comment by vortice3D** [comment]
Thanks **Julien**:

It will be great.

**Comment by julien-moreau** [comment]
@vortice3D done!
I'll let you know once you'll be able to use the v2. Wich is pretty soon :)

**Comment by Issabln** [comment]
V4 is out. Anything new regarding the undo-function?

**Comment by julien-moreau** [comment]
Hey @Issabln,
Starting from the V3 of the editor, almost all functions support undo/redo. I’m working on improving to support more and more operations. Don’t hesitate to report issues when you encounter an unavailable undo/redo operation :)
