### ISSUE TITLE
Builds for the editor are missing or unavailable in the readme 

### ISSUE THREAD

**Issue by HeadClot** [BabylonJS/Editor#340]
Hey a bit of a heads up for you @julien-moreau the builds for the editor at the moment are down or unavailable. I tried to get the latest version from the readme.md. 

Could you put the builds for the editor back up?

**Comment by HeadClot** [comment]
I just made a PR for this issue that fixes this.

https://github.com/BabylonJS/Editor/pull/341

**Comment by julien-moreau** [comment]
Hey @HeadClot !
Again, nice catch ! Thanks for pointing out this issue :)

I'm about to release the version 4.1.0 which has a full rework of the way to manage assets for projects. Are you interested to beta test it? Have you already started a project?

**Comment by HeadClot** [comment]
I would be interested in the beta test. I have not started a project yet but will be soon.

**Comment by julien-moreau** [comment]
Fixed and you can find the versions here: https://github.com/BabylonJS/Editor/blob/master/README.md#download-v410
