### ISSUE TITLE
Deletion of unused textures 

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#35]
Dear **Julien**:

In order to reach a more productive tool, we think the user should have a way to remove the unused textures from the project.

Now (as you know) we have a textures list, and we can add new ones but not to delete them.

Best regards.

**Comment by julien-moreau** [comment]
Working on it :)

**Comment by vortice3D** [comment]
Thanks for your time **Julien**.

**Comment by julien-moreau** [comment]
Added!

**Comment by julien-moreau** [comment]
Deploying!
Don't hesitate to open another issue if you encounter a bug :)

**Comment by julien-moreau** [comment]
To clean the textures list, just reload it using the "reload" button. It will refresh the list and clean the unused textures
<img width="1155" alt="capture d ecran 2017-12-01 a 20 43 17" src="https://user-images.githubusercontent.com/2620127/33500199-606c03e2-d6d8-11e7-99d3-e9939965d765.png">
<img width="1000" alt="capture d ecran 2017-12-01 a 20 43 22" src="https://user-images.githubusercontent.com/2620127/33500201-609dc008-d6d8-11e7-87a1-a609e648be98.png">

**Comment by vortice3D** [comment]
Ok, Julien, thank you.
