### ISSUE TITLE
Typo in BabylonJS Editor webpage

### ISSUE THREAD

**Issue by eherozhao** [BabylonJS/Editor#350]
http://editor.babylonjs.com/

> Using the lastest version of Babylon.JS, the Editor allows creating highly customizable 3D web projet skeletons based on the powerful ES6 modules version of Babylon.JS.

Should these be "**latest**" and "**project**"?

**Comment by bmcbarron** [comment]
@eherozhao , I'll bet a [PR would be welcome](https://softwareengineering.stackexchange.com/a/419026/411172).

**Comment by eherozhao** [comment]
Will push a PR for it. Close the issue.

**Comment by julien-moreau** [comment]
Hi @eherozhao !
Thanks for reporting! I just fixed the typo and published the fix.
Thanks :)
