### ISSUE TITLE
Error in Chrome and Chromium

### ISSUE THREAD

**Issue by Lozamded** [BabylonJS/Editor#354]
I export a test project but only works on Firefox https://www.deephorizons.cl/babyloncar/
In chrome and chromiun based browsers give me these errors

![Babylon Chrome error](https://user-images.githubusercontent.com/9289861/159151878-a90c7009-14b2-4567-9b85-092d66517e81.png)

Sorry for my bad english

**Comment by moshuying** [comment]
![image](https://user-images.githubusercontent.com/37231523/159395260-5867aa12-6ade-439d-85df-d59a77aa6994.png)

**Comment by Lozamded** [comment]
I fix it changing the dependencies in the package.json file of the project to 4.2.1
reinstalling the dependencies using « npm i » in the folder project
and making another build of the project

**Comment by julien-moreau** [comment]
Hi @Lozamded and @moshuying !
The fix mentioned by @Lozamded is the one :)

Nice catch !
