### ISSUE TITLE
“BabylonJS Editor” is damaged and can’t be opened. You should move it to the Trash

### ISSUE THREAD

**Issue by ioridev** [BabylonJS/Editor#359]
mac m1pro maros12.3
Installer: BabylonJS Editor-4.1.0-arm64.dmg
http://editor.babylonjs.com/electron/4.1.0/BabylonJS%20Editor-4.1.0-arm64.dmg

**Comment by eherozhao** [comment]
Did you install it successfully? Would you mind uploading the screenshot of the issue?

Basically if it only said it's unsecure and should move to the Trash, you can go to Application folder and right click open that. More contexts will be helpful.

**Comment by eherozhao** [comment]
> mac m1pro maros12.3 Installer: BabylonJS Editor-4.1.0-arm64.dmg http://editor.babylonjs.com/electron/4.1.0/BabylonJS%20Editor-4.1.0-arm64.dmg

Did you install it successfully? Would you mind uploading the screenshot of the issue?

Basically if it only said it's unsecure and should move to the Trash, you can go to Application folder and right click open that. More contexts will be helpful.

**Comment by ioridev** [comment]
I could right-click to open it!
Thank you very much.
