### ISSUE TITLE
One-step browse+assign texture 

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#36]
Hi **Julien**:

More suggestions/wishes from **Vórtice** here.

With the current version of the editor, one can choose the texture from a list (of scene loaded textures) or to load it by browsing.

The case is that when you browse the texture, the editor loads it in the scene, but doesn´t assign it immediately ; so you must to do the additional step of assign from the drop-down list.

Could be implemented this browse(load)+assign texture in only one step?

Best regards.

**Comment by julien-moreau** [comment]
Working on it :)

**Comment by vortice3D** [comment]
Ok **Julien**.

Thank you very much for your time.

**Comment by julien-moreau** [comment]
Just fixed! I'll let you know when deployed :)

**Comment by julien-moreau** [comment]
Deployed!

**Comment by vortice3D** [comment]
Hi **Julien**:

Thanks for the effort.

Only one more thing about this. Do you think it could be possible, please, to make the "Browse" button on textures, automatically open windows browser instead of going to the Editor's textures list and browse from there?

I'll see forward to hearing from you.

Best regards.
