### ISSUE TITLE
Import mesh utility method

### ISSUE THREAD

**Issue by JuliaABurch** [BabylonJS/Editor#361]
I'm working on a plugin that was started before the release of `4.1.0` and tries to add `.gltf` assets with customized behavior to the current scene open in the editor. 

It would be nice to have access to the functionality defined in the [MeshHandler](https://github.com/BabylonJS/Editor/blob/9a1a7948c68243c033ef81aa4a7fba4159347602/src/renderer/editor/components/assets-browser/files/handlers/mesh.tsx#L148)'s `OnDropInPreview` method, so that the editor loads the `.gltf` (with all of the appropriate metadata defined and properties set, etc) as if the user had dragged it from the asset browser.

**Comment by julien-moreau** [comment]
Hi @JuliaABurch !

Nice catch!
I'm opening the API so you'll have access to that helper methods :)
