### ISSUE TITLE
Error when launching the game

### ISSUE THREAD

**Issue by danilofaugusto** [BabylonJS/Editor#362]
Hello,

I've downloaded the latest version of the editor just now, created an empty project, added two primitive meshes, and clicked on the play button. I'm getting the below error right off the bat. Would you know what workaround I could use? Thanks

**-----------------------------------------------**
Exporting Final Scene

Serializing scene...
Copying tools...
Computing project configuration...
Configuring scripts...
Copying shader files...
Successfully generated scene at D:/BabylonProjects/TestProject/scenes/scene

Failed to start playing scene

An error happened: Cannot find module 'D:/BabylonProjects/TestProject/build/src/scenes/tools.js' Require stack: - C:/Users/1545-6IRONV4/AppData/Local/Programs/BabylonJS Editor/resources/app.asar/build/src/renderer/play/inline-play.js - C:/Users/1545-6IRONV4/AppData/Local/Programs/BabylonJS Editor/resources/app.asar/build/src/renderer/editor/components/preview.js - C:/Users/1545-6IRONV4/AppData/Local/Programs/BabylonJS Editor/resources/app.asar/build/src/renderer/editor/assets/materials.js - C:/Users/1545-6IRONV4/AppData/Local/Programs/BabylonJS Editor/resources/app.asar/build/src/renderer/editor/scene/utils.js - C:/Users/1545-6IRONV4/AppData/Local/Programs/BabylonJS Editor/resources/app.asar/build/src/renderer/editor/editor.js - C:/Users/1545-6IRONV4/AppData/Local/Programs/BabylonJS Editor/resources/app.asar/build/src/renderer/editor/index.js - C:\Users\1545-6IRONV4\AppData\Local\Programs\BabylonJS Editor\resources\app.asar\html\editor.html

**Comment by danilofaugusto** [comment]
Hey @julien-moreau! 

You were absolutely right! After I installed Node.JS everything worked great. 

As I downloaded it from here, http://editor.babylonjs.com/, I was totally unaware of the dependency. Maybe adding a warning to that download page will mitigate newbies coming here and bothering you folks in the future hehe

Thanks for the help!

**Comment by eherozhao** [comment]
If the reply has answered your question @danilofaugusto. Do you mind close the issue on your side? Thank you.
