### ISSUE TITLE
Not a clear UI with cameras

### ISSUE THREAD

**Issue by eherozhao** [BabylonJS/Editor#364]
![image](https://user-images.githubusercontent.com/36955586/163243448-a91a2ea0-befc-47aa-a51e-4177443f9836.png)
When switching the cameras, I cannot see which one is using until I click one again. Is there anyway to see which camera is used in the Editor?

**Comment by julien-moreau** [comment]
Hi @eherozhao !

Thanks for that feedback! You are right, the icon should be a "checked" icon to tell the user which camera is the active camera. I'm adding it right now.

**Comment by eherozhao** [comment]
I saw this change on the new 4.2.0 Editor. Thank you @julien-moreau !
