### ISSUE TITLE
Noob question installing the editor

### ISSUE THREAD

**Issue by alFrame** [BabylonJS/Editor#372]
I am trying to get this up and running. Not a programmer, hence I was delighted to find an editor for BJS. So, I am sorry if this seems like a dumb question or problem :)

Now several issues came up.
- The download link here (all the way at the bottom) is a 404: http://editor.babylonjs.com/
- The link on the main page on here is not downloading anything (Download (v4.1.0)): https://github.com/BabylonJS/Editor
  - I got it to download by copy and pasting the link: http://editor.babylonjs.com/electron/4.1.0/BabylonJS%20Editor%20Setup%204.1.0.exe
  - But then the downloaded BabylonJS Editor Setup 4.1.0.exe does nothing when double clicked. Even allowing it after the Windows (downloaded from the Internet) warning.
- Under releases there's source.zip and a source.tar.gz which I don't know how to deal with as it seems a full copy of the repository.

Is there a step by step how to get the editor running on my machine?

**Comment by julien-moreau** [comment]
Hi @alFrame !

I'm sorry for that, can you tell me what's your machine configuration?
- OS ?
- x64 or ARM?

Clicking on the links you shared (http://editor.babylonjs.com/) work for me and I don't get any 404 :(

Using released or repository needs you to install all the necessary developers tools. I think that's what you don't want to
I think we can find why you can't install the editor on your environment.

Because the package is not yet signed, maybe your antivirus is blocking the execution of the exe

**Comment by alFrame** [comment]
Hi @julien-moreau, Thanks for your reply!

I am on Intel running Windows 10 Pro. No anti virus whatsoever. Only Windows Defender. A dialog came up asking if I was sure I wanted to install the app, which I confirmed. But the nothing happened. No dialog came up and I did not find any process in the taskmanager.

Sorry for the confusion on the 404. The editor page does work. It's the download link at the end of the page that goes to 404: https://github.com/BabylonJS/Editor/tree/release/4.0.0

Thanks!

**Comment by eherozhao** [comment]
@alFrame It looks like the outdated documentation link issue. Feel free to contribute the fix if you want.

**Comment by alFrame** [comment]
@eherozhao Thank you for chiming in. I don't think we're talking about the same link. It's not a link in the documentation. It's on the official editor page. I would not know how I can contribute there other than pointing it out. I think the link should go to the github page https://github.com/BabylonJS/Editor so people always get pointed to the main github page and then can download the latest.

I might also point out that none of the links work properly on the github page either. Right clicking and "save link as..." works, but has to be confirmed, which I have never ever seen. Might be a new protective level by the browser :).

https://user-images.githubusercontent.com/27587287/167624107-fe12ac59-8e46-4aa5-941f-d5738662807c.mp4

Good news is that I managed to install it now by choosing "Run as Administrator".

Wohoo! I sure will have more questions. By making an editor you do attract artists that probably now little to nothing about programming. I hope I can be of help there to improve the editor.
