### ISSUE TITLE
SSAO2 Rendering Pipeline samples capped at 8

### ISSUE THREAD

**Issue by Quas94** [BabylonJS/Editor#376]
The number of samples is capped at a value of `8`, which isn't enough - still resulting in a very large number of horizontal artifacts for me.

![ssao2](https://user-images.githubusercontent.com/8134499/167600283-450dfe96-7ae6-4717-a198-9387e017d688.png)

I had a look in the code and found `private _getSSAO2Inspector(): React.ReactNode` in `src/renderer/editor/components/inspectors/scene/rendering-inspector.tsx` - it has `samples` set to `max={32}` - but it doesn't appear to be in use, or at the very least it's not what's rendering the section in the screenshot above.

**Comment by julien-moreau** [comment]
Hi @Quas94 

This tool is related to the babylonjs inspector. I suggest that you post your feedback/request on the forum so the Babylon.JS core team will answer :)

Thanks!

Babylon.JS Forum: https://forum.babylonjs.com/
