### ISSUE TITLE
Attribute "Use Roughness From Metallic Texture Green" doesn't work... take 2

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#38]
Hi **Julien**:

About the closed "Attribute "Use Roughness From Metallic Texture Green" doesn't work" issue, we see that now the BJS docs (v3.1) says you have:
- red channel for ambient occlusion;
- green channel for roughness
- and blue channel for metallic.

This has been changed from previous versions.

Anyway we can´t see any update in the textures of the editor scene when we set/unset the channels check-boxes.

Best regards.

**Comment by julien-moreau** [comment]
Thanks for reporting!
I'm changing the labels right now :)

**Comment by julien-moreau** [comment]
Ok just found the issue, I'm deploying!

**Comment by julien-moreau** [comment]
Deployed!

**Comment by vortice3D** [comment]
Ok, **Julien**, thank you very much.

One more think, please. If you doesn't check to use specific metallic and roughness channels, what are the default ones the engine is going to select?

We understand that red is the default metallic channel, isn't it?

Best regards.
