### ISSUE TITLE
On editor.babylonjs.com/ , the link to this GitHub repo doesn't work

### ISSUE THREAD

**Issue by ttmc** [BabylonJS/Editor#388]
If you go to the website at http://editor.babylonjs.com/ and scroll to the bottom, you will find the paragraph:

> The Editor source code is fully open source sharing the same licence as Babylon.JS. All code is available on [Github](https://github.com/BabylonJS/Editor/tree/release/4.0.0) and is open to all contributions/feedbacks. 

The link on the word GitHub doesn't work. It links to https://github.com/BabylonJS/Editor/tree/release/4.0.0 

Here is the source for that:

https://github.com/BabylonJS/Editor/blob/f75153246ba6dfd9ccc64d369ca48f104b4719e0/website/src/contents/home.tsx#L123

I suggest linking to https://github.com/BabylonJS/Editor/ instead.

P.S. GitHub is written with a capital 'H' in the middle of the word.

**Comment by julien-moreau** [comment]
Hey @ttmc good catch!
Thanks I'm fixing asap
