### ISSUE TITLE
Reflection probes "way of use"

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#39]
Hi **Julien**:

Always testing this awesome tool, we are now focus on reflection probes functionality.

We find that it could be more "ergonomic" to have attached the probe to the mesh in only one-step (by instance from Attach to Mesh).

Now you need to click "Attach to Mesh" in the probe, and then to do an additional step consisting in go to the PBR material and replace the reflection color with the probe one.

Best regards.

**Comment by julien-moreau** [comment]
Working on it :)

**Comment by julien-moreau** [comment]
Fixed!

**Comment by vortice3D** [comment]
Dear **Julien**:

Thanks for the support.

Best regards.
