### ISSUE TITLE
Feature Request - JS13k Mode

### ISSUE THREAD

**Issue by BoldBigflank** [BabylonJS/Editor#391]
The JS13k game jam is coming up soon, and BabylonJS is an option for creating games. 

https://js13kgames.com/webxr

It would be nice if the editor were able to make builds that follow js13k standards, such as:
* Instead of including the babylonjs library, load from CDN Link
* Use a more aggressive build minification, possibly rollup

I'd love some feedback on these and other ways to optimize, or whether you think it's even possible and why.

**Comment by julien-moreau** [comment]
Hey @BoldBigflank !
Nice idea ! The build system in the editor is open. The index.html file can be modified as wanted and only the « watch » and « build » scripts must be available in the package.json. That means if you want to use rollup or whatever just add the command line in the « watch » and « build » scripts in package.json. It is not necessary to include babylonjs in your build if you tell your packer that « @babylonjs/core/* » etc modules are located in a global variable named « BABYLON » on window or whatever.

Have you already tried the editor to make sure it fits your requirements for the game jam? I mean speed development etc.

**Comment by BoldBigflank** [comment]
Thanks for the tips! I have looked into the editor a little bit, and originally I just wanted a tool that I could visualize a bunch of geometric shapes and export a json with the transforms/options of each, but this one is so close to a Unity editor that I feel I could make the game in it, provided I can get the exported package to be 1/1000th of the size.
