### ISSUE TITLE
How to open gui window in Editor?

### ISSUE THREAD

**Issue by pxim** [BabylonJS/Editor#393]
![image](https://user-images.githubusercontent.com/5111701/185067630-94216af3-5c40-4ae7-b4dd-824557bcbea1.png)
How to open gui window in Editor?

**Comment by eherozhao** [comment]
I am not sure I understand the question. Is the window in the image you uploaded the Editor GUI?

**Comment by pxim** [comment]
> I am not sure I understand the question. Is the window in the image you uploaded the Editor GUI?

I know now, this refers to the GUI code fragment file introduced in BabylonEditor. 
I thought I can use Gui Editor directly in the BabylonEditor.

**Comment by eherozhao** [comment]
Sounds good. So if you have been unblocked, feel free to close the issue.
