### ISSUE TITLE
About materials (deletion or augmentation)

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#40]
Hi **Julien**:

Another functionality we found would be very nice to have is the **BJS Editor** is the ability to delete the default materials, or else to transform then from _Standard_ to _PBR_.

What are your thoughts on this?

Thanks for your time.

**Comment by julien-moreau** [comment]
Looks like a good idea!
Then we assume that:
- specular properties become reflectivity properties
- diffuse properties become albedo properties
- no metallic properties will be transformed

Are you ok with that ?

**Comment by vortice3D** [comment]
Ok **Julien**, please do as you prefer.

Our interest here is mainly to be able to change the type of material from Standard to PBR; in order to not need to start from scratch, but with the help of your PBR default scene.

Best regards.

**Comment by julien-moreau** [comment]
Hey @vortice3D, just added the way to convert standard materials to PBR materials https://github.com/BabylonJS/Editor/commit/95ecc7fc8f307bbaf8a178db585d4582de65d3de

I'm adding the way to clean the not used materials :)

**Comment by julien-moreau** [comment]
Added a way to remove unused materials (only Standard Materials right now but will work with all other material types soon): https://github.com/BabylonJS/Editor/commit/665310007f1993614cfa273308b5139fcc452557

**Comment by vortice3D** [comment]
Hi **Julien**:

Reviewing your great new updates to the **BJS Editor** we can find easily the way to de-assign the materials but not how to remove/delete them.

Any help with this?

**Comment by vortice3D** [comment]
Hi again **Julien**:

Excuse me... just found the option in the menu.

The list is not refreshed until it has the focus but we can live with it.

Thanks for your time.

**Comment by julien-moreau** [comment]
Oh you are right I totally forgot to tell you where to find the button =O
Right, I’ll fix the list to be refreshed, good catch !

**Comment by julien-moreau** [comment]
Just fixed and deployed :)
