### ISSUE TITLE
Where Can I Find the Source Code of the Editor for Web Version?

### ISSUE THREAD

**Issue by fruithardcandy** [BabylonJS/Editor#406]
Like Title My Question ~~ 

Where Can I Find the Source Code of the Editor for Web Version Like http://editor.babylonjs.com/v3/ 
![image](https://user-images.githubusercontent.com/8188489/209647599-927445f3-b894-4fec-a98e-32b09453c80d.png)

**Comment by Xbathy** [comment]
commit history maybe or realeases list?

**Comment by julien-moreau** [comment]
You can find it here: https://github.com/BabylonJS/Editor/releases/tag/v3.1.2
