### ISSUE TITLE
Crash after setting "sphereGlass" reflection texture to "none"

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#41]
Hi **Julien**:

In the default scene, I've disconnected the environment on each PBR material in order to use the global one in the scene node.

No issues on each material, but when setting the "sphereGlass" material reflection texture to "none", I get the following error and the scene go non-responsive and everything, except the environment, disappears.

Following is the web-console dump:

> TypeError: reflectionTexture is undefined
> 
> babylon.max.js:36149:25
> PBRBaseMaterial.prototype.isReadyForSubMesh
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:36149:25
> 
> Mesh.prototype.render
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:24166:22
> 
> SubMesh.prototype.render
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:26151:13
> 
> RenderingGroup.renderUnsorted
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:17603:17
> 
> RenderingGroup.prototype.render
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:17503:17
> 
> RenderingManager.prototype.render
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:17299:21
> 
> Scene.prototype._renderForCamera
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:20501:13
> 
> Scene.prototype._processSubCameras
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:20553:17
> 
> Scene.prototype.render
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:20755:17
> 
> n</n.prototype.update
> http://editor.babylonjs.com/libs/preview%20release/babylon.editor.js:4:30868
> 
> n</n.prototype.createRenderLoop/<
> http://editor.babylonjs.com/libs/preview%20release/babylon.editor.js:4:30294
> 
> Engine.prototype._renderLoop
> http://editor.babylonjs.com/libs/preview%20bjs/babylon.max.js:9057:25
> <anónimo> self-hosted:952:17

**Comment by julien-moreau** [comment]
Thanks for reporting!
@sebavan can you check that? 
I noticed that theses lines (https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/PBR/babylon.pbrBaseMaterial.ts#L832) do not check if reflectionTexture exists :(

**Comment by julien-moreau** [comment]
Just fixed and deployed thanks to @sebavan !
