### ISSUE TITLE
Add code signing

### ISSUE THREAD

**Issue by wright-luda** [BabylonJS/Editor#412]
I downloaded http://editor.babylonjs.com/electron/4.5.0/BabylonJS%20Editor-4.5.0-arm64.dmg
After installing, it will not run, as the OS says that file is damaged and cannot be run. I'm running it on a Mac M1 with MacOS 13.1

**Comment by julien-moreau** [comment]
The problem is the package is not signed and comes from an http address. This problem is being partially fixed using https but the package remains still not signed. This is an issue on my side as I must sign my builds. I keep this issue opened.

**Comment by clement128** [comment]
Same problem for 4.6 arm64 on Mac M1, any workaround ? thanks

**Comment by wright-luda** [comment]
Thank you. Confirming that `xattr -cr ` fixes this issue.
