### ISSUE TITLE
Console.log is not work?

### ISSUE THREAD

**Issue by tidus2020** [BabylonJS/Editor#414]
`public onInitialized(): void {
        console.log("inited....")
}`
can't see any thing.

**Comment by julien-moreau** [comment]
logs coming from the console are not supported when you play in the editor. Please use:

```typescript
import { Tools } from "@babylons/core/Misc/tools";
...
Tools.Log("initiated...")
```

I suggest that you use the Babylon.JS forum for future questions (https://forum.babylonjs.com/) because you can get help from other users as well. Thanks a lot :)
