### ISSUE TITLE
Environment texture lost on re-opening

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#42]
Hi **Julien**:

Please check the following behavior.

When using a global environment texture, it is lost on re-opening. It is disconnected from the global Scene environment but also deleted from the textures list.

So one has to re-import the texture and re-apply it.

Thanks for your time.

**Comment by julien-moreau** [comment]
Working on it in Babylon.js

**Comment by vortice3D** [comment]
Ok **Julien**:

Thank you very much for your time on this issue... and the others you've closed today.

Best regards.

**Comment by julien-moreau** [comment]
Finally fixed and deployed ! :)
