### ISSUE TITLE
Export/convert animated glb

### ISSUE THREAD

**Issue by shibberd** [BabylonJS/Editor#420]
Not really an issue but more of a work flow request.

Our client has sent an animated glb and usdz file but we need to change the animation.
They cant send the source files probably from 3DSMax so is there a workflow which can export the glb as fbx which retains the animation within.

We can then re animate and export from Maya using Babylon.
Thanks for any help.
Steve

**Comment by julien-moreau** [comment]
Hi @shibberd !

Unfortunately, the editor supports only GLTF/GLB serialization. Also, the support of loading is limited where it's unable to serialize as FBX :(

Maybe you can use Sketchfab to convert them to FBX or find a proper plugin that enables to load GLB files properly in your modeler

For questions and help don't hesitate to post on the forum (https://forum.babylonjs.com/), the community might have a log of ideas to help in your process
