### ISSUE TITLE
Questions about meshes

### ISSUE THREAD

**Issue by danhue22daw** [BabylonJS/Editor#421]
Hi it's my first time using Babylon and I'm trying to make a few meshes but I have a problem, maybe it's basic but I don't find the way.
Is there any option to merge meshes (like Ctrl+J on Blender)? 
I tried putting the meshes I want to merge into an empty mesh but that doesn't seem to work because when I try to clone it I only get the empty mesh and not the ones inside that.

And another question, I'm trying to import a .glb file from blender to Babylon Editor but I don't find the way to do it, how I can do it?

Thanks in advance.

**Comment by julien-moreau** [comment]
Hi @danhue22daw !

Unfortunately merging meshes is possible by selecting all meshes to merge in the graph -> right click -> merge meshes. Take care to select only meshes.

To add meshes in your scene (glb, babylon etc.) you can drag'n'drop them from the assets panel like this: https://doc.babylonjs.com/communityExtensions/editor/assets/addingMeshes

For questions, don't hesitate to use the forum instead (https://forum.babylonjs.com/) so other members can help you too :)
