### ISSUE TITLE
Bug: Setting '@visibleInInspector' to the spacebar in the inspector causes 'Press the key to set' to repeat

### ISSUE THREAD

**Issue by ClementineAccount** [BabylonJS/Editor#424]
Reproduction: Attempt to set 'spacebar' for any key exposed by a code such as `@visibleInInspector("KeyMap", "Backward Key", "s".charCodeAt(0))`

Example shown here using the First Person Shooter template:
![spacebarBug](https://user-images.githubusercontent.com/26779639/232773859-88b3e0f6-af8d-493b-b86b-5679723e2fc0.gif)

**Comment by julien-moreau** [comment]
Hey @ClementineAccount nice catch!! Just fixed, will be released ASAP

**Comment by julien-moreau** [comment]
Deployed :)
