### ISSUE TITLE
Bug: Download link not working properly

### ISSUE THREAD

**Issue by Sovea** [BabylonJS/Editor#433]
### Environment:
Apple M1 Pro macOS 13.3.1 (a) 
Chrome：113.0.5672.126（stable） (arm64)
Microsoft Edge：113.0.1774.42 (stable) (arm64)

### Issue：
When i click the download link in the README.md file, Chrome will do nothing, and Edge will give me a warning - "Can not download safely".

<img width="361" alt="image" src="https://github.com/BabylonJS/Editor/assets/49814337/a9655788-3d0a-496e-a9af-20ca27a46e34">

### Fix:
I think we should update the download link to https protocol.

**Comment by julien-moreau** [comment]
Thanks @Sovea !
