### ISSUE TITLE
Removing unused materials doesn't clear "unused then" textures.

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#44]
Hi **Julien**:

When using the remove unused materials feature, it clears the materials but not the textures.

Maybe it is the intentional behavior (I think you could say something about it in other issue's thread ), isn't it?

Kind regards.

**Comment by julien-moreau** [comment]
I think you are right, the textures should be cleaned too. I'm updating right now :)

**Comment by julien-moreau** [comment]
Deployed!
