### ISSUE TITLE
You can only open the particle edit window once.

### ISSUE THREAD

**Issue by ironsoul** [BabylonJS/Editor#45]
- Added a particle system to the plane in the scene.
- Clicked on the particle system in the outliner.
- Opened the Edit Window under Functions.
- Edited particle system(or don't doesn't make a difference), close the edit window.
- Try to open edit window a second time, it won't open.

On top of that, after using the edit window I can no longer add more particle systems.

**Comment by julien-moreau** [comment]
Good Catch!
Fixing ASAP :)

**Comment by julien-moreau** [comment]
It's Christmas! Just fixed and deployed :)
https://github.com/BabylonJS/Editor/commit/4e4b50da6117bc7cc8f2f529c9da768e37597498
