### ISSUE TITLE
Mesh Editing

### ISSUE THREAD

**Issue by netcinematics** [BabylonJS/Editor#46]
julien great work. I've been watching for a while, and forgive me if I simply missed it.... is there mesh editing feature at all? I am crafting large landscapes, and wrote some initial mesh editing code (babylon: click and key press move vertices x,y,z). Also, this can probably be extended in many ways.... is this a roadmap item? I would be honored to contribute a pull request if that is the state of things. Thx. :)

**Comment by julien-moreau** [comment]
Right now the editor do not provide this kind of tool but it's an excellent idea!
To be sure, do you mean exactly "mesh editing vertex per vertex" ? Or something like a terrain editor with elevation etc.? like this: https://discourse-cdn-sjc1.com/standard4/uploads/atomicgameengine/original/1X/fac59c79defb83e4eb9da3fdda397610e7350c2e.jpg

**Comment by julien-moreau** [comment]
Can you share a link of your work you have already done? :)

**Comment by JSRenaissance** [comment]
Yes, you were correct. Mesh Editor: vertex by vertex. The babylonJS code is not all that advanced. But it could work well with what you have developed. Here is a link to the discussion thread: 
http://www.html5gamedevs.com/topic/34397-solved-mesh-editor-edit-ribbon-vertices/?page=2
code is at the very end. :)  I see there are other ways to edit, and the terrain elevation idea is gr8 too.

**Comment by julien-moreau** [comment]
Just took a look on blender and 3ds Max, it looks like they already provide all the tools you need (terrain editor, height map generation etc), including vertices manipulations of course

I suggest to develop an extension you can use to fit your needs, let’s start the base of the extension and let you pull request :)

For my information, why do you need to manipulate vertices directly with in a Babylon scene ?

**Comment by JSRenaissance** [comment]
Yes, good to follow into the future and thank you for asking. The situation is unusual as you guess. The goal is a planet... as a skate-park. : )  In-between things is a need to make adjustments (on a single curvy hidden physics ribbon), which covers the blender.babylon's. : ) The initial trial worked very well, and could have stopped there. But! A surprise takeaway: the kids like editing! The edit-mode was far more enjoyable than originally thought. e.g. "Creative-Mode". And options are vast... as you know. :)
 Thank you sir, I will be in touch over the months. I'm off in Node, Electron, and PayPal - then I'll be back.  
Your editor is the best. So I share finding to you for your interest & expertise. That simple mesh editing has hidden potential! ~afalcon. : )

**Comment by JSRenaissance** [comment]
One other small thing, you probably know, the run-time edited ribbon was easily saved/loaded from json. New territory fyi... :)

**Comment by julien-moreau** [comment]
@netcinematics have you though about this feature?
Do you plan to add it into the editor? The plugins system looks now ready to welcome your :)

**Comment by netcinematics** [comment]
I plan to return to this yes. At the moment, into Electron Apps. Need to push to Steam. Then link up NodeJS Update Server. Then... back to fun stuff. UPDATE: did research into RoBlox Studio. They have a pretty awesome and full-featured mesh editor (different context).

**Comment by julien-moreau** [comment]
Analysed and will not be available in the editor has 3D modeler have more powerful tools to edit meshes
Thanks for the idea! :)
