### ISSUE TITLE
Why is the editor no longer updated?

### ISSUE THREAD

**Issue by BraveMomo** [BabylonJS/Editor#460]
It's been two years

**Comment by GhostCatcg** [comment]
Maybe not many people use it.

**Comment by julien-moreau** [comment]
Hey @BraveMomo @GhostCatcg 
The active branche is feature/5.0.0 https://github.com/BabylonJS/Editor/tree/feature/5.0.0 for now in order to prepare the version 5 that is still under development. Feel free to experiment it and ill more than happy to get your feedbacks !
