### ISSUE TITLE
Please provide the Windows 5.0 installation package, the official website currently only has the 4.7 installation package

### ISSUE THREAD

**Issue by BraveMomo** [BabylonJS/Editor#461]
![62bf0269bb1dc8019ba8d933f2268750](https://github.com/BabylonJS/Editor/assets/22335503/45dcf769-790b-42e8-8f39-ef5fae7ab40f)

**Comment by BraveMomo** [comment]
And the project relies on Babylon 6.0, not 7.0, please update as well

**Comment by BraveMomo** [comment]
And the project relies on Babylon 6.0, not 7.0, please update as well

**Comment by GhostCatcg** [comment]
> And the project relies on Babylon 6.0, not 7.0, please update as well

I think they are already updating it, on the feature/5.0.0 branch

**Comment by BraveMomo** [comment]
> > And the project relies on Babylon 6.0, not 7.0, please update as well
> 
> I think they are already updating it, on the feature/5.0.0 branch

5.0 seems to only have the source code, there is no packaging, Windows users seem to have to compile other things to run, I'm not very good at these, I hope to provide the installation package directly.

**Comment by julien-moreau** [comment]
Hey @BraveMomo, it has been done and available here: https://editor.babylonjs.com/download
