### ISSUE TITLE
Problems encountered with v5.0.0-alpha.1

### ISSUE THREAD

**Issue by wyd1520866381** [BabylonJS/Editor#462]
<img width="1494" alt="image" src="https://github.com/BabylonJS/Editor/assets/64176197/ec962b5b-3df8-4e71-92fe-14c125d357a8">

Problems encountered during initialization of the project

cpu: M1 Pro 
macos: 14.5

**Comment by julien-moreau** [comment]
Hey @wyd1520866381 !!
Thanks a lot for reporting!! I planned to remove this step in the UI and let the editor do it in background.
At the end, does the installation process succeeded and it was just a UI issue?
Thanks a lot for your answer

**Comment by wyd1520866381** [comment]
The project can be launched, but it seems to take a relatively long time to start, and what I see is a black screen, giving the impression that it might be stuck.

**Comment by julien-moreau** [comment]
This is why this dialog showing the progress is useless. I just pushed a fix where installing dependencies is done in background here: [c00e1dcfba455e7db1e9180795da23409c76886c](https://github.com/BabylonJS/Editor/commit/c00e1dcfba455e7db1e9180795da23409c76886c)

Thanks again for reporting
