### ISSUE TITLE
Package for Mac OS 15.0

### ISSUE THREAD

**Issue by shunmugam303** [BabylonJS/Editor#478]
Hello,
Mac OS 15.0.0
I created a build from the feature/5.0.0 branch. The package is getting created, but I'm unable to open it. When I try to open it, it throws an error.

**Comment by julien-moreau** [comment]
Hey @shunmugam303 thanks for reporting!!

Do you have a screenshot of the error so it can help me? I try to find a mac with macOS 15.x installed on it to test but in case I don't reproduce, the screenshot or the logs would be helpful.

Thanks a lot !

**Comment by shunmugam303** [comment]
hello @julien-moreau 
Thanks for your reply
I attached error logs, 
<img width="997" alt="Screenshot 2024-09-19 at 4 47 38 PM" src="https://github.com/user-attachments/assets/be5c6df0-301a-4820-a533-19d74ac4fcca">

[MacOS15.0  error.txt](https://github.com/user-attachments/files/17058054/MacOS15.0.error.txt)

**Comment by julien-moreau** [comment]
Hey @shunmugam303 thanks a lot !
It helped me and I pushed a fix on the same branch (`feature/5.0.0`). I updated my own mac on macOS 15 and reproduced the problem also. Now it works like a charm :)

Once you confirm that it works on your side, I close this issue
