### ISSUE TITLE
5.0.0 Project Template File

### ISSUE THREAD

**Issue by ndunks** [BabylonJS/Editor#479]
I just testing the 5.0.0 branch, but I can't get it run because missing the project template file. I don't know how to create it. Any help? 
![image](https://github.com/user-attachments/assets/249a953c-12b3-46ca-9d9f-f7e7facbd31e)

**Comment by ndunks** [comment]
Sorry, I found it in `build.js` file. my bad.

**Comment by IamYuZhiqiang** [comment]
> Sorry, I found it in `build.js` file. my bad.

So please how to fix the templates-missing error? I got the same issue.
