### ISSUE TITLE
Modifications events

### ISSUE THREAD

**Issue by devAxeon** [BabylonJS/Editor#48]
Hi,

Is there a way we can listen for all modifications ?
Something like:

`BABYLON.Editor.on("change", (object, attribute, value) => {
    //DO STUFF HERE
});`

Where "object" can be the mesh or the material edited, "attribute" can be "diffuseColor", and "value" the hexa of the diffuse for example ?

Regards,

**Comment by julien-moreau** [comment]
Sure I can add! :)
Are you using the V1 or the V2 of the Babylon.js Editor?

**Comment by julien-moreau** [comment]
The preview of the V2 is available here: http://editor.babylonjs.com/v2

**Comment by devAxeon** [comment]
I don't have any constraints about versions, V2 is ok for me ;)

Many thanks !!

**Comment by julien-moreau** [comment]
Hey, just added in the V2 here: https://github.com/BabylonJS/Editor/commit/bded1b722c8c4504c30473f66bc2dbb0de9058e1

I do not close the issue right now because I don't notify you for EVERY changes, will add more changes notifications in future :)

You can now type:
```
editor.core.onGlobalPropertyChange.add((result) => {
        console.log(result.object); // The modified object
        console.log(result.property); // The proeprty changed (as string)
        console.log(result.value); // New value after change
        console.log(result.initialValue); // Value before change
});
```

**Comment by julien-moreau** [comment]
@devAxeon fixed, all modifications are plugged to undo-redo :)
Closing the issue
