### ISSUE TITLE
Where have gone the rain particles?

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Editor#49]
Hi **Julen**:

First of all, let me congratulate you for this brand new version of "Da Editor".

From here only a, let's say trivial question.

Days ago I could take a brief look to the (online) V2 and it showed some very realistic raindrops in the scene, even with apparent floor bouncing.

I can´t see them now in the scene and the case is that I'm very interesting in study their implementation.

Best regards.

**Comment by vortice3D** [comment]
Ok, I was looking in trying [the](http://editor.babylonjs.com/) but the (beautiful) rainy scene was in [](http://editor.babylonjs.com/v2/).

I close this thread.

**Comment by julien-moreau** [comment]
Oh cool!
Anyway if you want to find the code you can reach the rain particles here: https://github.com/BabylonJS/Editor/blob/v2/src/editor/tools/default-scene.ts#L225
And the drop here: https://github.com/BabylonJS/Editor/blob/v2/src/editor/tools/default-scene.ts#L248
