### ISSUE TITLE
Metalness parameter bug

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Editor#51]
- Choose an object that has Standard Material
- Click on Convert to PBR material
- Go to PBR properties and you will find "metalness" property MISSING (BUG)
- Deselect the object, select it again, add a metalness texture, check and uncheck boxes for metalness, deselect and select again.. and sometimes metalness property appears.

Please fix the metalness property so it is always visible and it works as expected.
By default the object is pitch black and metalness cannot be altered.

It would make sense to be able to modify the metalness without adding a texture.
The same for the roughness, it would make sense to be able to add it without adding a texture

**Comment by julien-moreau** [comment]
Thanks for reporting !
Will fix ASAP :)

**Comment by julien-moreau** [comment]
Fixed and deployed :)
For information: the editor checks if the "metalness" property is undefined before drawing it. Setting a metallic texture will define this property. Then, the editor is able to draw it.
Once you specify a texture, the editor hardly refresh the view for you (you'll have to scroll down again to retrieve your properties)

Thank you for reporting :)
