### ISSUE TITLE
[V2] Edit Panel Scrollbar is too hard to scroll

### ISSUE THREAD

**Issue by gotwig** [BabylonJS/Editor#58]
Because of the new Golden Layout Manager the scrollbar is not easily usable.

A solution is to set the css property overflow for child div element (class="dg main taller-than-window") of  id="SCENE-TOOL"   : 

overflow: visible;

**Comment by julien-moreau** [comment]
Excellent !
Can you pull request ? :)

**Comment by gotwig** [comment]
yes but please wait for tomorrow :)

**Comment by julien-moreau** [comment]
No problems :)
