### ISSUE TITLE
[V2] New font

### ISSUE THREAD

**Issue by gotwig** [BabylonJS/Editor#60]
We should decide on a font.

sans-serif would be a good font

**Comment by gotwig** [comment]
I found a combo of this:
Source Sans Pro,Arial,sans-serif
https://fonts.google.com/specimen/Source+Sans+Pro
What you think?

**Comment by julien-moreau** [comment]
Absolutely agree :)

**Comment by julien-moreau** [comment]
Thanks @gotwig ! :)
