### ISSUE TITLE
[V2] WASD, QE controls

### ISSUE THREAD

**Issue by gotwig** [BabylonJS/Editor#63]
Add controls for WASD, think about Q/E controls (not sure how to implement) for height up ( q ) and down ( e )

**Comment by gotwig** [comment]
My first patch will add traditional WASD to editor. Something like Q / E is not available builtin

**Comment by gotwig** [comment]
Ok, any idea how to properly integrate Q / E :D for going higher and going lower?

**Comment by julien-moreau** [comment]
Not sure, if it is not avlaible in BABYLON.FreeCamera you should create a PR on Babylonjs :)

**Comment by gotwig** [comment]
Im not sure they would want this in BabylonJS itself, and they dont even got WASD controls yet :x 
But this is the relevant place: 
https://github.com/BabylonJS/Babylon.js/blob/0c2ba69ea3de0f130697f703ff1e3a563fe08b9d/src/Cameras/Inputs/babylon.freeCameraKeyboardMoveInput.ts#L84
