### ISSUE TITLE
[V2] Resize issue

### ISSUE THREAD

**Issue by gotwig** [BabylonJS/Editor#69]
If you got some additional plugins open , you reload page, they get restored.

If you now click on different tabs at some point the resizing for the plugins doesnt work anymore.

Any idea?

**Comment by julien-moreau** [comment]
Hum, you are right! Did not noticed that, will check ASAP because I have no idea except:
Maybe plugins must listen their layout resize

**Comment by julien-moreau** [comment]
Fixed
