### ISSUE TITLE
Undo operation and animation

### ISSUE THREAD

**Issue by chan056** [BabylonJS/Editor#72]
Hi, I'm new in Babylon, some problems appear when I use Babylon editor. 

Firstly, why no undo operation exists? After I delele a mesh or light, if I want them back, what should I do? 
Then, about animation, I can edit/play animation in loop mode, how should I stop the animation? Should I must delete the animation?

Overall, great work.

**Comment by julien-moreau** [comment]
Are you using the V1 of the editor?
If yes:
- no undo/redo (coming soon with V2)
- when you click on the « Play » button on top-left in the toolbar ? Or on the button in the édition tools on the left ?
