### ISSUE TITLE
Release time for v2

### ISSUE THREAD

**Issue by yanyufish** [BabylonJS/Editor#73]
Hi. Could you tell me when will be the estimate release time for v2? Thanks.

**Comment by julien-moreau** [comment]
Hey, I'm happy that you ask :)
I plan to release the v2 during July. Time for last fixes etc.
Anyway you can access the "stable preview" here: http://editor.babylonjs.com/v2/

What feature are you expected exactly that is not present ?

**Comment by gabrieljbaker** [comment]
I would love the ability to load a gltf model right from the editor.

**Comment by julien-moreau** [comment]
From now you can drag’n’drop gltf and glb files into the editor to load the scenes. You can also export scenes as gltf and glb

I’ll update the editor to the latest bjs versions and everything will work file :)

**Comment by Nodragem** [comment]
Can't wait the release!

**Comment by julien-moreau** [comment]
It is planned to end of July! =D
For instance, you can test the latest version here: http://editor.babylonjs.com/v2/
An Electron version will be available as well :)

**Comment by Nodragem** [comment]
Yes, the link was already above :P 
There are things puzzling me though in that new version.

**Comment by julien-moreau** [comment]
That would be cool to know what ! =D
Bug & usage reports are welcome so I can update the editor to fit your needs :)

**Comment by Nodragem** [comment]
I pressed on the send button unwillingly, so it was an incomplete comment :D 
Now you can see the edited message with all my suggestions above.
I guess we could open a new issue based on them ^^.

**Comment by julien-moreau** [comment]
Awesome feedbacks!
I’ll create the issues one by one or you can create them :)
Will take the easier feedbacks today and integrate them. For the rest, I’ll let you know once done

**Comment by Nodragem** [comment]
Cool! please create the issue, cause I won't have the time today (I think you did already) :)

**Comment by julien-moreau** [comment]
Hey, for the screenshot above about default layout, I just added a way to save your layout when you exit the editor (electron and web) so you'll retrieve your layout everytime :)
