### ISSUE TITLE
(V2) Gizmo Tool missing features

### ISSUE THREAD

**Issue by gotwig** [BabylonJS/Editor#74]
After Move/Rotate/Scale the edit panel doesnt update its values live according to the current setting.

UI Tooltips and Keyboard shortcuts missing

In-Scene Gizmo Should be in front of everything (currently scene tooltips are in front of gizmo)

Thank you!

**Comment by julien-moreau** [comment]
Thanks for reporting! Will try to plug an event on gizmos and update the values :)

**Comment by julien-moreau** [comment]
Update display : https://github.com/BabylonJS/Editor/commit/0fc2b400e6c371e98caf2de50dd75b429ae8e5e4
