### ISSUE TITLE
What if I want to attach one script to many game objects?

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Editor#81]
what if I want to attach one script to many game objects? if this is possible or becomes possible, then please do not repeat Unity's mistake: provide a way to quickly know which game objects are attached to a specific script (the opposite of the scenegraph which tells us which scripts are attached to a specific game object).

**Comment by Nodragem** [comment]
I was thinking:
The real scripts could be living outside the game objects while gameobjects just need to have a reference to them. 

I think, for now, this is how it is: 
If you create a script on gameobject1 and copy it to gameobject2 and now you delete the script in gameobject1 and in gameobject2, then, you don't have the script anymore.
Is that right?
 
What could be better is: 
When you add a script to an gameobject1, the editor creates a script and a reference to that script, then when you "copy" your script to gameobject2, the editor just adds a reference to the script to gameobject2. Then, when you delete the script from gameobject1 and 2, the editor just deletes the reference to the script. 
Thus, at the end, the script still exists and you can still add it to other gameobject.

This would means that in you Behaviour Editor you could have a several view:
- show behaviours of the selected object
- show unused behaviours
- show all behaviours

And then you would also have an option to show the gameobjects attached to the current script.

**Comment by julien-moreau** [comment]
Working on :)

**Comment by julien-moreau** [comment]
Done!
I'll add in future more graphics tools to attach scripts. Now it is an option in the scene graph (context menu). I plan to add an "assets" panel
