### ISSUE TITLE
Could you add more options when we right-click an object in the scenegraph or 3D window?

### ISSUE THREAD

**Issue by julien-moreau** [BabylonJS/Editor#83]
could you add more options when we right-click an object in the scenegraph or 3D window: add Script, add Material, etc...

**Comment by julien-moreau** [comment]
Hey @Nodragem, just added "Set Material" and "Add Script"
Do you have more ideas ?

**Comment by Nodragem** [comment]
After I click on "Set Material", the Material Viewer opens and I can change the material of the sphere I right-clicked. That's neat :)

However, if I click on another sphere in the 3D view and click on a material in the Material Viewer, the material is changed on the first sphere (the one I right-clicked in the scenegraph earlier).

I guess that what you want is that the material changes on the sphere that is currently selected. Probably it was the case before you add the "Set Material". Maybe "Set Material" is redundant then :/

Concerning other "Add" buttons, I was thinking about a "New Material" option that opens the "Add Material Menu" directly. In the Add Material Menu I would also put the Shader Material (Custom Material), which would open the Material Editor with a new Custom Material.

Speaking of the Material Editor, I think that it should be renamed to Shader Material Editor or Shader Editor, as I understand there are PBR Materials, Standard Material, and even more. Shader Materials are one type of Material, right? Following this logic, the default name of the files would not be Custom Material but Shader Material. And following the logic we had with scripts, you would ask for a name, although the default proposed would be "Shader Material1".

I also thought about an option "Open Shader Material Editor", to quicky open the Shader Editor on the Shader Material of that object if it has one? 

However, thinking again about this right-click options, I realise that we may not need to have this right-click options to access the materials and scripts of an object if where they were represented in the scenegraph. Imagine that the scripts are show under the objects they are attached to in the scenegraph. Now, you can open its attached scripts just by clicking on them ^^ same idea with the Shader Material.

What do you think?
