### ISSUE TITLE
[V2] Preview Window toolbar and main toolbar

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Editor#86]
Now that we have toolbar on the top of the Preview window, we could use this space to make some tools easier to access, here some suggestions:
- move the "move", "scale", "rotation" tools in the Preview window's toolbar, as we only needs them in the 3D view.
- the main toolbar ("Project", "Edit", etc) could be reduced to 1 row to avoid wasting space?  the buttons "Play", "Test", "Test and Debug" would be on the same row as "Project" and "Edit" but aligned on the center?
- I am not certain of what the Test and Test and Debug buttons are doing... but the Play button could be moved to the Preview window's toolbar, as that's playing the preview?
- would it be easy to add "Play/Pause", "Stop", "Restart" options when previewing?

**Comment by julien-moreau** [comment]
Unfortunately the UI library I'm using doesn't permit this kind on feature for instance :( (placing elements aligned center)
For the play buttons I'll use the other issue you just created :)
