### ISSUE TITLE
Remove Area under Scene Preview

### ISSUE THREAD

**Issue by gotwig** [BabylonJS/Editor#96]
The area thats supposed to hold the extensions cant be hidden. Maybe remove it or at least hide it if its not used.

**Comment by gotwig** [comment]
![removearea](https://user-images.githubusercontent.com/1532942/43736289-5e9eed42-99bd-11e8-9493-5a36eebf4355.png)

**Comment by julien-moreau** [comment]
Right, once the panel has 0 tabs :)
